#!/usr/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2010, 2011, Oracle and/or its affiliates. All rights reserved.
#

. /lib/svc/share/smf_include.sh

if [ -z "$SMF_FMRI" ]; then
	echo "this script can only be invoked by smf(5)"        
	exit $SMF_EXIT_ERR_NOSMF
fi

#
# The real daemon is not started in a shared stack zone. But we need to
# create a dummy background process to preserve contract lifetime.
#
smf_configure_ip
if [ $? -eq 1 ] ; then
	(while true ; do sleep 3600 ; done) & 
        exit $SMF_EXIT_OK
fi

/lib/inet/in.mpathd

[ $? -eq 0 ] || exit $SMF_EXIT_ERR_FATAL

exit $SMF_EXIT_OK
