'\" te
.\"  Copyright (c) 1997, Sun Microsystems, Inc.  All Rights Reserved
.TH yield 2 "20 Jul 1993" "SunOS 5.11" "System Calls"
.SH NAME
yield \- yield execution to another lightweight process
.SH SYNOPSIS
.LP
.nf
#include <unistd.h>

\fBvoid\fR \fByield\fR(\fBvoid\fR);
.fi

.SH DESCRIPTION
.sp
.LP
The \fByield()\fR function causes the current lightweight process to yield its execution in favor of another lightweight process with the same or greater priority.
.SH SEE ALSO
.sp
.LP
\fBthr_yield\fR(3C)
