#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libc_i18n/sparc/Makefile

include ../Makefile.com

EXTN_CFLAGS =
EXTN_CPPFLAGS =	-Dsparc
EXTN_LINTFLAGS=

install: all $(ROOTLIB_PIC)
