#
# Copyright (c) 2005, 2010, Oracle and/or its affiliates. All rights reserved.
#
#

MDBSRC=../../../../../../src/cmd/mdb

CPPFLAGS += -I$(MDBSRC)/common

$(TONICBUILD)include $(CLOSED)/Makefile.tonic
