#
# Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
#
#
#	This Makefile defines the build rules for the directory uts/sun4v
#	and its children. These are the source files which sun4v
#	"implementation architecture" dependent.
#
#	The following two-level ordering must be maintained in this file.
#	  Lines are sorted first in order of decreasing specificity based on
#	  the first directory component.  That is, sun4v rules come before
#	  sparc rules come before common rules.
#
#	  Lines whose initial directory components are equal are sorted
#	  alphabetically by the remaining components.

#
#	Section 1a: C object build rules
#

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/bmc/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/sbmc/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/ipmi/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/memtest/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4/io/memtest/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/memtest/%.s
	$(COMPILE.s) -o $@ $<

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4/io/memtest/%.s
	$(COMPILE.s) -o $@ $<

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/ncp/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/ncp/%.s
	$(COMPILE.s) -o $@ $<

$(OBJS_DIR)/n2cp.o:		$(UTSCLOSED)/sun4v/io/n2cp/n2cp.c	\
				$(UTSCLOSED)/sun4v/io/n2cp/n2cp.il
	$(COMPILE.c) $(UTSCLOSED)/sun4v/io/n2cp/n2cp.il	\
	 -o $@ $(UTSCLOSED)/sun4v/io/n2cp/n2cp.c
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/n2cp/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4v/io/n2cp/%.s
	$(COMPILE.s) -o $@ $<

#
#	Section 1b: Lint `object' build rules
#

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/bmc/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/sbmc/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/ipmi/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/memtest/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4/io/memtest/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/memtest/%.s
	@($(LHEAD) $(LINT.s) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4/io/memtest/%.s
	@($(LHEAD) $(LINT.s) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/ncp/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/ncp/%.s
	@($(LHEAD) $(LINT.s) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/n2cp/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4v/io/n2cp/%.s
	@($(LHEAD) $(LINT.s) $< $(LTAIL))
