#
# Copyright (c) 2010, Oracle and/or its affiliates. All rights reserved.
#


UTSTREE=$(UTSCLOSED)

include $(UTSBASE)/sun4v/Makefile.sun4v.shared
$(TONICBUILD)include $(UTSCLOSED)/../Makefile.tonic
