#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#

UTSTREE=$(UTSCLOSED)

include $(UTSBASE)/sun4v/Makefile.targ.shared
