#
# Copyright (c) 2005, 2011, Oracle and/or its affiliates. All rights reserved.
#
# uts/common/Makefile.rules
#
# This Makefile defines the file build rules for the encumbered files
# under uts/common. These source files may be considered common to all
# SunOS systems.
#
#	The following two-level ordering must be maintained in this file.
#	  Lines are sorted first in order of decreasing specificity based on
#	  the first directory component.  That is, sun4u rules come before
#	  sparc rules come before common rules.
#
#	  Lines whose initial directory components are equal are sorted
#	  alphabetically by the remaining components.

UTSCLOSEDCOM = $(UTSCLOSED)/common

#
#	Section 1a: C objects build rules
#

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnx/src/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnx/570x/driver/common/lmdev/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnxe/src/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnxe/577xx/common/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnxe/577xx/drivers/common/ecore/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnxe/577xx/drivers/common/lm_device/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnxe/577xx/drivers/common/lm_device/fw/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnxe/577xx/drivers/common/lm_device/l4/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)
$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/bnxe/577xx/drivers/common/lm_device/l5/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/bmc/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:              $(UTSCLOSEDCOM)/io/sbmc/%.c
	$(COMPILE.c) -I $(UTSCLOSEDCOM)/io/ipmi -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/ipmi/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:                $(UTSCLOSEDCOM)/io/cpqary3/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/ib/clients/sdpib/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/ixgb/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/llc2/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/pcmcia/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/pcn/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/sata/adapters/marvell88sx/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/sata/adapters/bcm_sata/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/se/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:	$(UTSCLOSEDCOM)/io/usb/clients/usbser/usbser_edge/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/scsi_vhci/fops/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/scu/base/source/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/scu/ossl/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/scu/sati/source/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/scu/scic/sds/source/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/scu/scif/sas/source/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/adapters/scu/util/source/%.c 
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/io/scsi/targets/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDCOM)/klm/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

#
#	Section 1b:	Lint `objects'
#

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/bnx/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/bmc/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/sbmc/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/ipmi/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:              $(UTSCLOSEDCOM)/io/cpqary3/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/ib/clients/sdpib/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/ixgb/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/llc2/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/pcmcia/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/pcn/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/se/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:	$(UTSCLOSEDCOM)/io/usb/clients/usbser/usbser_edge/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:	$(UTSCLOSEDCOM)/io/sata/adapters/marvell88sx/%.c 
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:	$(UTSCLOSEDCOM)/io/sata/adapters/bcm_sata/%.c 
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/scsi/adapters/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/scsi/adapters/scsi_vhci/fops/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/scsi/adapters/scu/ossl/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/io/scsi/targets/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDCOM)/klm/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))
