#
# Copyright (c) 2010, Oracle and/or its affiliates. All rights reserved.
#
#

UTSTREE=$(UTSCLOSED)

include $(UTSBASE)/sun4u/Makefile.sun4u.shared
$(TONICBUILD)include $(UTSCLOSED)/../Makefile.tonic
