#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libc_i18n/i386/Makefile

include ../Makefile.com

EXTN_CFLAGS =	$(CTF_FLAGS)
EXTN_CPPFLAGS =	-Di386
EXTN_LINTFLAGS=	-erroff=E_SUPPRESSION_DIRECTIVE_UNUSED

install: all $(ROOTLIB_PIC)
