#
# Copyright (c) 2002, 2011, Oracle and/or its affiliates. All rights reserved.
#
# lib/libike/i386/Makefile

include ../Makefile.com

install: stubinstall all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)

stubinstall: stub $(STUBROOTLIBS) $(STUBROOTLINKS)
