#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 1994, 2011, Oracle and/or its affiliates. All rights reserved.
#
# psm/stand/lib/Makefile.lib

include $(TOPDIR)/Makefile.master
include $(TOPDIR)/Makefile.psm

STANDDIR	= $(TOPDIR)/stand
PSMSTANDDIR	= $(TOPDIR)/psm/stand

SYSHDRDIR	= $(STANDDIR)
SYSLIBDIR	= $(STANDDIR)/lib/$(MACH)

PSMSYSHDRDIR	= $(PSMSTANDDIR)
PSMBOOTLIBDIR	= $(PSMSTANDDIR)/lib/boot/$(MACH)
PSMNAMELIBDIR	= $(PSMSTANDDIR)/lib/names/$(MACH)
PSMPROMLIBDIR	= $(PSMSTANDDIR)/lib/promif/$(MACH)

#
# Lint rules (adapted from Makefile.uts)
#
LHEAD		= $(ECHO) "\n$@";
LTAIL		=
LINT_DEFS	+= -Dlint

#
# For building lint objects
#
LINTFLAGS.c	= -nsxum -erroff=E_BAD_PTR_CAST_ALIGN
LINTFLAGS.c	+= $(ALWAYS_LINT_DEFS)
LINTFLAGS64.c	= -nsxum -erroff=E_BAD_PTR_CAST_ALIGN -m64
LINTFLAGS64.c	+= $(ALWAYS_LINT_DEFS)
LINT64.c	= $(LINT) $(LINTFLAGS64.c) $(LINT_DEFS) $(CPPFLAGS) -c
LINT.c		= $(LINT) $(LINTFLAGS.c) $(LINT_DEFS) $(CPPFLAGS) -c
LINT.s		= $(LINT.c)

#
# For building lint libraries
#
LINTFLAGS.lib	= -nsxumy
LINTFLAGS.lib	+= $(ALWAYS_LINT_DEFS)
LINT.lib	= $(LINT.ln) $(LINTFLAGS.lib) $(LINT_DEFS) $(CPPFLAGS)

#
# For complete pass 2 cross-checks
#
LINTFLAGS.2	= -nsxm
LINT.2		= $(LINT) $(LINTFLAGS.2) $(LINT_DEFS) $(CPPFLAGS)

#
# Simple rule for making objs/%.ln from %.c and %.s
#

objs/%.ln:	%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))
	@$(MV) $(@F) $@

objs/%.ln:	%.s
	@($(LHEAD) $(LINT.c) $< $(LTAIL))
	@$(MV) $(@F) $@

