#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.

. /lib/svc/share/smf_include.sh

if [ ! -x /usr/lib/ilomconfig.builtin ]; then
        echo "/usr/lib/ilomconfig.builtin not found or not executable"
        exit SMF_EXIT_ERR_FATAL
fi


case "$1" in 

'start')
	
        x=0
	while [ $x -le 4 ]
	do

	    /usr/lib/ilomconfig.builtin enable interconnect
            ret=$?

	    if [ $ret -eq 0 ] ; then
		exit $SMF_EXIT_OK
	    fi

	    sleep 30

	    x=$(( $x + 1 ))
	done

	;;


*)
	echo "Usage: $0 { start }"
	;;
esac
# Return OK even if enable did not complete. If SP is powered-off
# it will not be possible to enable interconnect.
exit $SMF_EXIT_OK
