#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"

LIB = mtst_AuthenticAMD_15.so

OBJS = \
	opt_bu.o \
	opt_common.o \
	opt_dc.o \
	opt_ic.o \
	opt_ls.o \
	opt_nb.o \
	opt_main.o

LIBSRCDIR = ../../common/opteron

include ../../Makefile.cpumod

LDLIBS += -lc

include ../../Makefile.cpumod.targ
