.\" ident	"%Z%%M%	%I%	%E% SMI"
.\"
.\" 
.\"
.\" "Copyright 2000 Sun Microsystems, Inc."
.\" "All rights reserved"
.\" "Use is subject to license terms."
.TH sccscp 1 "20 May 1992"
.SH NAME
.I sccscp
\- copy SCCS files under CodeManger control
.SH SYNOPSIS
.B sccscp
[-r] [-g] [-d] filename1 [filename2...] target
.SH DESCRIPTION
.I sccscp
is to be used to duplicate sccs files which are under CodeManager
control.  sccscp will copy the files or directories given
on the command line, it will then "uniqueify"
the SMID for the s-dot file.
.LP
.I sccscp
should be used any time your are duplicating part of a workspace
under CodeManager control.  
.SH OPTIONS
.TP 10
.B \-r
If file n is a directory, 
.B sccscp
will copy the directory and all its files, including any
subdirectories and their files; 
.I target must be a directory.
.TP
.B \-g
Don't do SCCS gets after copying the s-dot files.  Normally 
g-files are extracted after they are copied.  
.TP
.B \-e
Copy most recent delta if file is currently checked out.
.TP
.B \-d
set debug mode.
