.\" ident	"%Z%%M%	%I%	%E% SMI"
.\"
.\" 
.\"
.\" "Copyright 2000 Sun Microsystems, Inc."
.\" "All rights reserved"
.\" "Use is subject to license terms."
.TH sccsrm 1 "20 May 1992"
.SH NAME
.I sccsrm
\- remove SCCS files under Avocet control
.SH SYNOPSIS
.B sccsrm
[-f] <filename> ...
.SH DESCRIPTION
.I sccsrm
is to be used to remove sccs files which are under Avocet
control.  sccsrm will rename the files or directories given
on the command line to the following format:
.LP
.RS 5
.nf
<filename>	->	.del-<filename>-<month>-<day>.{pid}
.fi
.RE
.LP
The trailing pid is optional and will only be appended to the filename
if it is required to make a unique .del filename.
