#!/usr/sbin/sh
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"%Z%%M%	%I%	%E% SMI"

case $1 in
'start')
	if [ -x /etc/llc2/llc2_start ]; then
		/etc/llc2/llc2_start
	fi
	;;
'stop')
	if [ -x /etc/llc2/llc2_start ]; then
		/usr/lib/llc2/llc2_config -U
	fi
	;;
*)
	echo "Usage: $0  { start | stop }"
	exit 1
esac
exit 0
