#
# Copyright (c) 2003, 2011, Oracle and/or its affiliates. All rights reserved.
#
# lib/libsasl/sparc/Makefile

include ../Makefile.com

install: stubinstall all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)

stubinstall: stub $(STUBROOTLIBS) $(STUBROOTLINKS)
