#!/usr/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
#

. /lib/svc/share/smf_include.sh

#
# commands
#
IPADM=/usr/sbin/ipadm

if [ -z "$SMF_FMRI" ]; then
        echo "this script can only be invoked by smf(5)"        
        exit $SMF_EXIT_ERR_NOSMF
fi

#
# System-wide forwarding (either ipv4 or ipv6) must be enabled before
# load balancing daemon can be started.
#
v4fwding=`$IPADM show-prop -c -o current -p forwarding ipv4 2>/dev/null`
v6fwding=`$IPADM show-prop -c -o current -p forwarding ipv6 2>/dev/null`
if [ -z "$v4fwding" -o "$v4fwding" = "off" ]; then
	if [ -z "$v6fwding" -o "$v6fwding" = "off" ]; then
		echo "ipv4 forwarding or ipv6 forwarding must be enabled for "\
		    "load balancing daemon to start"
		exit $SMF_EXIT_ERR_CONFIG
	fi
fi

#
# Start the ilbd daemon.
#
if /usr/lib/inet/ilbd ; then
	exit $SMF_EXIT_OK
else
        exit $SMF_EXIT_ERR_FATAL
fi
