#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/raidcfg_plugins/mpt/amd64/Makefile
#

include ../Makefile.com
include $(SRC)/lib/Makefile.lib.64

.KEEP_STATE:

install: all $(ROOTLIBS64)
