'\" te
.\" Copyright (c) 2002, 2011, Oracle and/or its affiliates. All rights reserved.
.TH eqnchar 5 "20 May 2011" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
eqnchar \- special character definitions for eqn
.SH SYNOPSIS
.LP
.nf
eqn  /usr/share/lib/pub/eqnchar \fIfilename\fR |  troff \fIoptions\fR
.fi

.LP
.nf
neqn  /usr/share/lib/pub/eqnchar \fIfilename\fR |  troff \fIoptions\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fBeqnchar\fR command contains \fBnroff\fR(1) and \fBtroff\fR(1) character definitions for constructing characters that are not available on the Graphic Systems typesetter. These definitions are primarily intended for use with \fBeqn\fR(1) and \fBneqn\fR(1). It contains definitions for the characters listed in the following table.
.sp
To view the special characters, see the online manual page.
.SH FILES
.sp
.LP
\fB/usr/share/lib/pub/eqnchar\fR
.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5)  for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Availabilitytext/doctools
.TE

.SH SEE ALSO
.sp
.LP
\fBeqn\fR(1), \fBnroff\fR(1), \fBtroff\fR(1), \fBattributes\fR(5) 
