'\" te
.\"  Copyright (c) 1996, Sun Microsystems, Inc.  All Rights Reserved
.TH extensions 5 "20 Dec 1996" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
extensions \- localedef extensions description file
.SH DESCRIPTION
.sp
.LP
A localedef extensions description file or \fIextensions\fR file defines various extensions for the \fBlocaledef\fR(1) command.
.sp
.LP
The localedef extensions description file provides:
.RS +4
.TP
.ie t \(bu
.el o
\fBEUC\fR code set width information via the \fBcswidth\fR keyword: \fBcswidth bc1\|:\|sw1,bc2\|:\|sw2,bc3\|:\|sw3\fRwhere \fBbc1\fR, \fBbc2\fR, and \fBbc3\fR indicate the number of bytes (byte count) per character for \fBEUC\fR codesets \fB1\fR, \fB2\fR, and \fB3\fR, respectively. \fBsw1\fR, \fBsw2\fR, and \fBsw3\fR indicate screen width for \fBEUC\fR codesets \fB1\fR, \fB2\fR, and \fB3\fR, respectively.
.RE
.RS +4
.TP
.ie t \(bu
.el o
Other extensions which will be documented in a future release.
.RE
.SH SEE ALSO
.sp
.LP
\fBlocale\fR(1), \fBlocaledef\fR(1), \fBenviron\fR(5), \fBlocale\fR(5) 
