'\" te
.\"  Copyright (c) 1997, Sun Microsystems, Inc.  All Rights Reserved
.TH iconv_646 5 "28 Apr 1997" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
iconv_646 \- code set conversion tables for ISO 646
.SH DESCRIPTION
.sp
.LP
The following code set conversions are supported:
.sp

.sp
.TS
tab() box;
cw(.61i) |cw(1.22i) |cw(1.22i) |cw(.61i) |cw(1.83i) 
cw(.61i) |cw(1.22i) |cw(1.22i) |cw(.61i) |cw(1.83i) 
.
Code Set Conversions Supported
_
CodeSymbolTarget CodeSymbolTarget Output
_
ISO 646646ISO 8859-18859US ASCII
_
ISO 646de646deISO 8859-18859German
_
ISO 646da646daISO 8859-18859Danish
_
ISO 646en646enISO 8859-18859English ASCII
_
ISO 646es646esISO 8859-18859Spanish
_
ISO 646fr646frISO 8859-18859French
_
ISO 646it646itISO 8859-18859Italian
_
ISO 646sv646svISO 8859-18859Swedish
.TE

.SH CONVERSIONS
.sp
.LP
The conversions are performed according to the following tables. All values in the tables are given in octal.
.SS "ISO 646 (US ASCII) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646 to ISO 8859-1, all characters in ISO 646 can be mapped unchanged to ISO 8859-1
.SS "ISO 646de (GERMAN) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646de to ISO 8859-1, all characters not in the following table are mapped unchanged.
.sp

.sp
.TS
tab() box;
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
.
Conversions Performed
_
ISO 646deISO 8859-1ISO 646deISO 8859-1
_
100247173344
133304174366
134326175374
135334176337
.TE

.SS "ISO 646da (DANISH) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646da  to ISO 8859-1, all characters not in the following table are mapped unchanged.
.sp

.sp
.TS
tab() box;
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
.
Conversions Performed
_
ISO 646daISO 8859-1ISO 646daISO 8859-1
_
133306173346
134330174370
135305175345
.TE

.SS "ISO 646en (ENGLISH ASCII) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646en to ISO 8859-1, all characters not in the following table are mapped unchanged.
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
cw(2.75i) |cw(2.75i) 
.
Conversions Performed
_
ISO 646enISO 8859-1
_
043243
.TE

.SS "ISO 646es (SPANISH) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646es to ISO 8859-1, all characters not in the following table are mapped unchanged.
.sp

.sp
.TS
tab() box;
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
.
Conversions Performed
_
ISO 646esISO 8859-1ISO 646esISO 8859-1
_
100247173260
133241174361
134321175347
135277
.TE

.SS "ISO 646fr (FRENCH) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646fr to ISO 8859-1, all characters not in the following table are mapped unchanged.
.sp

.sp
.TS
tab() box;
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
.
Conversions Performed
_
ISO 646frISO 8859-1ISO 646frISO 8859-1
_
043243173351
100340174371
133260175350
134347176250
135247
.TE

.SS "ISO 646it (ITALIAN) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646it to ISO 8859-1, all characters not in the following table are mapped unchanged.
.sp

.sp
.TS
tab() box;
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
.
Conversions Performed
_
ISO 646itISO 8859-1ISO 646itISO 8859-1
_
043243140371
100247173340
133260174362
134347175350
135351176354
.TE

.SS "ISO 646sv (SWEDISH) to ISO 8859-1"
.sp
.LP
For the conversion of ISO 646sv to ISO 8859-1, all characters not in the following table are mapped unchanged.
.sp

.sp
.TS
tab() box;
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
cw(1.38i) |cw(1.38i) |cw(1.38i) |cw(1.38i) 
.
Conversions Performed
_
ISO 646svISO 8859-1ISO 646svISO 8859-1
_
100311140351
133304173344
134326174366
135305175345
136334176374
.TE

.SH FILES
.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/iconv/*.so\fR \fR
.ad
.RS 30n
.rt  
conversion modules
.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/iconv/*.t\fR \fR
.ad
.RS 30n
.rt  
conversion tables
.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/iconv/iconv_data\fR \fR
.ad
.RS 30n
.rt  
list of conversions supported by conversion tables
.RE

.SH SEE ALSO
.sp
.LP
\fBiconv\fR(1), \fBiconv\fR(3C), \fBiconv\fR(5) 
