'\" te
.\" Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
.TH locale_alias 5 "13 Apr 2011" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
locale_alias \- locale name aliases and their corresponding canonical locale names
.SH DESCRIPTION
.sp
.LP
There are two sets of locale name aliases that are accepted and supported in the system:
.RS +4
.TP
1.
Locale name aliases that are accepted and mapped to corresponding canonical locale names, if any, during locale selection process as specified in \fBsetlocale\fR(3C) and message object or message catalog processing as specified in \fBgettext\fR(1), \fBcatopen\fR(3C), and \fBgettext\fR(3C).
.sp
During the mapping process, the codeset name portion of the locale name aliases are normalized by extracting only alphanumeric characters with to-lower case conversions to have a better success ratio of possible mappings. As an example, with this normalization, a locale name alias such as \fBAR_AA.UTF-8\fR is normalized into \fBAR_AA.utf8\fR as a search domain value prior to actual comparisons to a set of pre-normalized locale alias names in internal mapping table to find the canonical locale name.
.sp
The supported locale name aliases in machine order are shown at below:
.sp
.in +2
.nf
                Locale Name Alias        Canonical Locale Name
                -----------------        ---------------------
                AR_AA                    ar_AA.UTF-8
                AR_AA.UTF-8              ar_AA.UTF-8
                AR_AE                    ar_AE.UTF-8
                AR_AE.UTF-8              ar_AE.UTF-8
                AR_BH                    ar_BH.UTF-8
                AR_BH.UTF-8              ar_BH.UTF-8
                AR_DZ                    ar_DZ.UTF-8
                AR_DZ.UTF-8              ar_DZ.UTF-8
                AR_EG                    ar_EG.UTF-8
                AR_EG.UTF-8              ar_EG.UTF-8
                AR_JO                    ar_JO.UTF-8
                AR_JO.UTF-8              ar_JO.UTF-8
                AR_KW                    ar_KW.UTF-8
                AR_KW.UTF-8              ar_KW.UTF-8
                AR_LB                    ar_LB.UTF-8
                AR_LB.UTF-8              ar_LB.UTF-8
                AR_MA                    ar_MA.UTF-8
                AR_MA.UTF-8              ar_MA.UTF-8
                AR_OM                    ar_OM.UTF-8
                AR_OM.UTF-8              ar_OM.UTF-8
                AR_QA                    ar_QA.UTF-8
                AR_QA.UTF-8              ar_QA.UTF-8
                AR_SA                    ar_SA.UTF-8
                AR_SA.UTF-8              ar_SA.UTF-8
                AR_SY                    ar_SY.UTF-8
                AR_SY.UTF-8              ar_SY.UTF-8
                AR_TN                    ar_TN.UTF-8
                AR_TN.UTF-8              ar_TN.UTF-8
                AR_YE                    ar_YE.UTF-8
                AR_YE.UTF-8              ar_YE.UTF-8
                AS_IN                    as_IN.UTF-8
                AS_IN.UTF-8              as_IN.UTF-8
                AZ_AZ                    az_AZ.UTF-8
                AZ_AZ.UTF-8              az_AZ.UTF-8
                BE_BY                    be_BY.UTF-8
                BE_BY.UTF-8              be_BY.UTF-8
                BG_BG                    bg_BG.UTF-8
                BG_BG.UTF-8              bg_BG.UTF-8
                BN_IN                    bn_IN.UTF-8
                BN_IN.UTF-8              bn_IN.UTF-8
                CA_ES                    ca_ES.UTF-8
                CA_ES.UTF-8              ca_ES.UTF-8
                CA_ES.UTF-8@euro         ca_ES.UTF-8
                CA_ES@euro               ca_ES.UTF-8
                CS_CZ                    cs_CZ.UTF-8
                CS_CZ.UTF-8              cs_CZ.UTF-8
                CY_GB                    cy_GB.UTF-8
                CY_GB.UTF-8              cy_GB.UTF-8
                DA_DK                    da_DK.UTF-8
                DA_DK.UTF-8              da_DK.UTF-8
                DE_AT                    de_AT.UTF-8
                DE_AT.UTF-8              de_AT.UTF-8
                DE_AT.UTF-8@euro         de_AT.UTF-8
                DE_AT@euro               de_AT.UTF-8
                DE_CH                    de_CH.UTF-8
                DE_CH.UTF-8              de_CH.UTF-8
                DE_DE                    de_DE.UTF-8
                DE_DE.UTF-8              de_DE.UTF-8
                DE_DE.UTF-8@euro         de_DE.UTF-8
                DE_DE@euro               de_DE.UTF-8
                DE_LU                    de_LU.UTF-8
                DE_LU.UTF-8              de_LU.UTF-8
                DE_LU.UTF-8@euro         de_LU.UTF-8
                DE_LU@euro               de_LU.UTF-8
                EL_GR                    el_GR.UTF-8
                EL_GR.UTF-8              el_GR.UTF-8
                EN_AU                    en_AU.UTF-8
                EN_AU.UTF-8              en_AU.UTF-8
                EN_BE                    en_BE.UTF-8
                EN_BE.UTF-8              en_BE.UTF-8
                EN_BE.UTF-8@euro         en_BE.UTF-8
                EN_BE@euro               en_BE.UTF-8
                EN_CA                    en_CA.UTF-8
                EN_CA.UTF-8              en_CA.UTF-8
                EN_GB                    en_GB.UTF-8
                EN_GB.UTF-8              en_GB.UTF-8
                EN_GB.UTF-8@euro         en_GB.UTF-8
                EN_GB@euro               en_GB.UTF-8
                EN_HK                    en_HK.UTF-8
                EN_HK.UTF-8              en_HK.UTF-8
                EN_IE                    en_IE.UTF-8
                EN_IE.UTF-8              en_IE.UTF-8
                EN_IE.UTF-8@euro         en_IE.UTF-8
                EN_IE@euro               en_IE.UTF-8
                EN_IN                    en_IN.UTF-8
                EN_IN.UTF-8              en_IN.UTF-8
                EN_NZ                    en_NZ.UTF-8
                EN_NZ.UTF-8              en_NZ.UTF-8
                EN_PH                    en_PH.UTF-8
                EN_PH.UTF-8              en_PH.UTF-8
                EN_SG                    en_SG.UTF-8
                EN_SG.UTF-8              en_SG.UTF-8
                EN_US                    en_US.UTF-8
                EN_US.UTF-8              en_US.UTF-8
                EN_ZA                    en_ZA.UTF-8
                EN_ZA.UTF-8              en_ZA.UTF-8
                ES_AR                    es_AR.UTF-8
                ES_AR.UTF-8              es_AR.UTF-8
                ES_BO                    es_BO.UTF-8
                ES_BO.UTF-8              es_BO.UTF-8
                ES_CL                    es_CL.UTF-8
                ES_CL.UTF-8              es_CL.UTF-8
                ES_CO                    es_CO.UTF-8
                ES_CO.UTF-8              es_CO.UTF-8
                ES_CR                    es_CR.UTF-8
                ES_CR.UTF-8              es_CR.UTF-8
                ES_DO                    es_DO.UTF-8
                ES_DO.UTF-8              es_DO.UTF-8
                ES_EC                    es_EC.UTF-8
                ES_EC.UTF-8              es_EC.UTF-8
                ES_ES                    es_ES.UTF-8
                ES_ES.UTF-8              es_ES.UTF-8
                ES_ES.UTF-8@euro         es_ES.UTF-8
                ES_ES@euro               es_ES.UTF-8
                ES_GT                    es_GT.UTF-8
                ES_GT.UTF-8              es_GT.UTF-8
                ES_HN                    es_HN.UTF-8
                ES_HN.UTF-8              es_HN.UTF-8
                ES_MX                    es_MX.UTF-8
                ES_MX.UTF-8              es_MX.UTF-8
                ES_NI                    es_NI.UTF-8
                ES_NI.UTF-8              es_NI.UTF-8
                ES_PA                    es_PA.UTF-8
                ES_PA.UTF-8              es_PA.UTF-8
                ES_PE                    es_PE.UTF-8
                ES_PE.UTF-8              es_PE.UTF-8
                ES_PR                    es_PR.UTF-8
                ES_PR.UTF-8              es_PR.UTF-8
                ES_PY                    es_PY.UTF-8
                ES_PY.UTF-8              es_PY.UTF-8
                ES_SV                    es_SV.UTF-8
                ES_SV.UTF-8              es_SV.UTF-8
                ES_US                    es_US.UTF-8
                ES_US.UTF-8              es_US.UTF-8
                ES_UY                    es_UY.UTF-8
                ES_UY.UTF-8              es_UY.UTF-8
                ES_VE                    es_VE.UTF-8
                ES_VE.UTF-8              es_VE.UTF-8
                ET_EE                    et_EE.UTF-8
                ET_EE.UTF-8              et_EE.UTF-8
                FI_FI                    fi_FI.UTF-8
                FI_FI.UTF-8              fi_FI.UTF-8
                FI_FI.UTF-8@euro         fi_FI.UTF-8
                FI_FI@euro               fi_FI.UTF-8
                FR_BE                    fr_BE.UTF-8
                FR_BE.UTF-8              fr_BE.UTF-8
                FR_BE.UTF-8@euro         fr_BE.UTF-8
                FR_BE@euro               fr_BE.UTF-8
                FR_CA                    fr_CA.UTF-8
                FR_CA.UTF-8              fr_CA.UTF-8
                FR_CH                    fr_CH.UTF-8
                FR_CH.UTF-8              fr_CH.UTF-8
                FR_FR                    fr_FR.UTF-8
                FR_FR.UTF-8              fr_FR.UTF-8
                FR_FR.UTF-8@euro         fr_FR.UTF-8
                FR_FR@euro               fr_FR.UTF-8
                FR_LU                    fr_LU.UTF-8
                FR_LU.UTF-8              fr_LU.UTF-8
                FR_LU.UTF-8@euro         fr_LU.UTF-8
                FR_LU@euro               fr_LU.UTF-8
                GU_IN                    gu_IN.UTF-8
                GU_IN.UTF-8              gu_IN.UTF-8
                HE_IL                    he_IL.UTF-8
                HE_IL.UTF-8              he_IL.UTF-8
                HI_IN                    hi_IN.UTF-8
                HI_IN.UTF-8              hi_IN.UTF-8
                HR_HR                    hr_HR.UTF-8
                HR_HR.UTF-8              hr_HR.UTF-8
                HU_HU                    hu_HU.UTF-8
                HU_HU.UTF-8              hu_HU.UTF-8
                ID_ID                    id_ID.UTF-8
                ID_ID.UTF-8              id_ID.UTF-8
                IS_IS                    is_IS.UTF-8
                IS_IS.UTF-8              is_IS.UTF-8
                IT_CH                    it_CH.UTF-8
                IT_CH.UTF-8              it_CH.UTF-8
                IT_IT                    it_IT.UTF-8
                IT_IT.UTF-8              it_IT.UTF-8
                IT_IT.UTF-8@euro         it_IT.UTF-8
                IT_IT@euro               it_IT.UTF-8
                JA_JP                    ja_JP.UTF-8
                JA_JP.UTF-8              ja_JP.UTF-8
                KK_KZ                    kk_KZ.UTF-8
                KK_KZ.UTF-8              kk_KZ.UTF-8
                KN_IN                    kn_IN.UTF-8
                KN_IN.UTF-8              kn_IN.UTF-8
                KO_KR                    ko_KR.UTF-8
                KO_KR.UTF-8              ko_KR.UTF-8
                LT_LT                    lt_LT.UTF-8
                LT_LT.UTF-8              lt_LT.UTF-8
                LV_LV                    lv_LV.UTF-8
                LV_LV.UTF-8              lv_LV.UTF-8
                MK_MK                    mk_MK.UTF-8
                MK_MK.UTF-8              mk_MK.UTF-8
                ML_IN                    ml_IN.UTF-8
                ML_IN.UTF-8              ml_IN.UTF-8
                MR_IN                    mr_IN.UTF-8
                MR_IN.UTF-8              mr_IN.UTF-8
                MS_MY                    ms_MY.UTF-8
                MS_MY.UTF-8              ms_MY.UTF-8
                MT_MT                    mt_MT.UTF-8
                MT_MT.UTF-8              mt_MT.UTF-8
                NL_BE                    nl_BE.UTF-8
                NL_BE.UTF-8              nl_BE.UTF-8
                NL_BE.UTF-8@euro         nl_BE.UTF-8
                NL_BE@euro               nl_BE.UTF-8
                NL_NL                    nl_NL.UTF-8
                NL_NL.UTF-8              nl_NL.UTF-8
                NL_NL.UTF-8@euro         nl_NL.UTF-8
                NL_NL@euro               nl_NL.UTF-8
                NO_NO                    no_NO.UTF-8
                NO_NO.UTF-8              no_NO.UTF-8
                OR_IN                    or_IN.UTF-8
                OR_IN.UTF-8              or_IN.UTF-8
                PA_IN                    pa_IN.UTF-8
                PA_IN.UTF-8              pa_IN.UTF-8
                PL_PL                    pl_PL.UTF-8
                PL_PL.UTF-8              pl_PL.UTF-8
                PT_BR                    pt_BR.UTF-8
                PT_BR.UTF-8              pt_BR.UTF-8
                PT_PT                    pt_PT.UTF-8
                PT_PT.UTF-8              pt_PT.UTF-8
                PT_PT.UTF-8@euro         pt_PT.UTF-8
                PT_PT@euro               pt_PT.UTF-8
                RO_RO                    ro_RO.UTF-8
                RO_RO.UTF-8              ro_RO.UTF-8
                RU_RU                    ru_RU.UTF-8
                RU_RU.UTF-8              ru_RU.UTF-8
                SH_SP                    sh_SP.UTF-8
                SH_SP.UTF-8              sh_SP.UTF-8
                SH_YU                    sh_YU.UTF-8
                SH_YU.UTF-8              sh_YU.UTF-8
                SK_SK                    sk_SK.UTF-8
                SK_SK.UTF-8              sk_SK.UTF-8
                SL_SI                    sl_SI.UTF-8
                SL_SI.UTF-8              sl_SI.UTF-8
                SQ_AL                    sq_AL.UTF-8
                SQ_AL.UTF-8              sq_AL.UTF-8
                SR_SP                    sr_SP.UTF-8
                SR_SP.UTF-8              sr_SP.UTF-8
                SR_YU                    sr_YU.UTF-8
                SR_YU.UTF-8              sr_YU.UTF-8
                SV_SE                    sv_SE.UTF-8
                SV_SE.UTF-8              sv_SE.UTF-8
                TA_IN                    ta_IN.UTF-8
                TA_IN.UTF-8              ta_IN.UTF-8
                TE_IN                    te_IN.UTF-8
                TE_IN.UTF-8              te_IN.UTF-8
                TH_TH                    th_TH.UTF-8
                TH_TH.UTF-8              th_TH.UTF-8
                TR_TR                    tr_TR.UTF-8
                TR_TR.UTF-8              tr_TR.UTF-8
                UK_UA                    uk_UA.UTF-8
                UK_UA.UTF-8              uk_UA.UTF-8
                UR_IN                    ur_IN.UTF-8
                UR_IN.UTF-8              ur_IN.UTF-8
                UR_PK                    ur_PK.UTF-8
                UR_PK.UTF-8              ur_PK.UTF-8
                VI_VN                    vi_VN.UTF-8
                VI_VN.UTF-8              vi_VN.UTF-8
                ZH_CN                    zh_CN.UTF-8
                ZH_CN.UTF-8              zh_CN.UTF-8
                ZH_HK                    zh_HK.UTF-8
                ZH_HK.UTF-8              zh_HK.UTF-8
                ZH_SG                    zh_SG.UTF-8
                ZH_SG.UTF-8              zh_SG.UTF-8
                ZH_TW                    zh_TW.UTF-8
                ZH_TW.UTF-8              zh_TW.UTF-8
                Zh_CN                    zh_CN.GB18030
                Zh_CN.GB18030            zh_CN.GB18030
                Zh_TW                    zh_TW.BIG5
                Zh_TW.big5               zh_TW.BIG5
                aa_DJ                    aa_DJ.ISO8859-1
                aa_DJ.iso88591           aa_DJ.ISO8859-1
                aa_DJ.utf8               aa_DJ.UTF-8
                aa_ER                    aa_ER.UTF-8
                aa_ER.utf8               aa_ER.UTF-8
                aa_ET                    aa_ET.UTF-8
                aa_ET.utf8               aa_ET.UTF-8
                af_ZA                    af_ZA.ISO8859-1
                af_ZA.iso88591           af_ZA.ISO8859-1
                af_ZA.utf8               af_ZA.UTF-8
                am_ET                    am_ET.UTF-8
                am_ET.utf8               am_ET.UTF-8
                an_ES                    an_ES.ISO8859-15
                an_ES.iso885915          an_ES.ISO8859-15
                an_ES.utf8               an_ES.UTF-8
                ar                       ar_EG.ISO8859-6
                ar_AA                    ar_AA.ISO8859-6
                ar_AE                    ar_AE.ISO8859-6
                ar_AE.iso88596           ar_AE.ISO8859-6
                ar_AE.utf8               ar_AE.UTF-8
                ar_BH                    ar_BH.ISO8859-6
                ar_BH.iso88596           ar_BH.ISO8859-6
                ar_BH.utf8               ar_BH.UTF-8
                ar_DZ                    ar_DZ.ISO8859-6
                ar_DZ.iso88596           ar_DZ.ISO8859-6
                ar_DZ.utf8               ar_DZ.UTF-8
                ar_EG                    ar_EG.ISO8859-6
                ar_EG.iso88596           ar_EG.ISO8859-6
                ar_EG.utf8               ar_EG.UTF-8
                ar_IN                    ar_IN.UTF-8
                ar_IN.utf8               ar_IN.UTF-8
                ar_IQ                    ar_IQ.ISO8859-6
                ar_IQ.iso88596           ar_IQ.ISO8859-6
                ar_IQ.utf8               ar_IQ.UTF-8
                ar_JO                    ar_JO.ISO8859-6
                ar_JO.iso88596           ar_JO.ISO8859-6
                ar_JO.utf8               ar_JO.UTF-8
                ar_KW                    ar_KW.ISO8859-6
                ar_KW.iso88596           ar_KW.ISO8859-6
                ar_KW.utf8               ar_KW.UTF-8
                ar_LB                    ar_LB.ISO8859-6
                ar_LB.iso88596           ar_LB.ISO8859-6
                ar_LB.utf8               ar_LB.UTF-8
                ar_LY                    ar_LY.ISO8859-6
                ar_LY.iso88596           ar_LY.ISO8859-6
                ar_LY.utf8               ar_LY.UTF-8
                ar_MA                    ar_MA.ISO8859-6
                ar_MA.iso88596           ar_MA.ISO8859-6
                ar_MA.utf8               ar_MA.UTF-8
                ar_OM                    ar_OM.ISO8859-6
                ar_OM.iso88596           ar_OM.ISO8859-6
                ar_OM.utf8               ar_OM.UTF-8
                ar_QA                    ar_QA.ISO8859-6
                ar_QA.iso88596           ar_QA.ISO8859-6
                ar_QA.utf8               ar_QA.UTF-8
                ar_SA                    ar_SA.ISO8859-6
                ar_SA.iso88596           ar_SA.ISO8859-6
                ar_SA.utf8               ar_SA.UTF-8
                ar_SD                    ar_SD.ISO8859-6
                ar_SD.iso88596           ar_SD.ISO8859-6
                ar_SD.utf8               ar_SD.UTF-8
                ar_SY                    ar_SY.ISO8859-6
                ar_SY.iso88596           ar_SY.ISO8859-6
                ar_SY.utf8               ar_SY.UTF-8
                ar_TN                    ar_TN.ISO8859-6
                ar_TN.iso88596           ar_TN.ISO8859-6
                ar_TN.utf8               ar_TN.UTF-8
                ar_YE                    ar_YE.ISO8859-6
                ar_YE.iso88596           ar_YE.ISO8859-6
                ar_YE.utf8               ar_YE.UTF-8
                as_IN.utf8               as_IN.UTF-8
                az_AZ.utf8               az_AZ.UTF-8
                be_BY                    be_BY.ISO8859-5
                be_BY.cp1251             be_BY.ANSI1251
                be_BY.utf8               be_BY.UTF-8
                bg_BG                    bg_BG.ISO8859-5
                bg_BG.cp1251             bg_BG.ANSI1251
                bg_BG.utf8               bg_BG.UTF-8
                bn_BD                    bn_BD.UTF-8
                bn_BD.utf8               bn_BD.UTF-8
                bn_IN                    bn_IN.UTF-8
                bn_IN.utf8               bn_IN.UTF-8
                br_FR                    br_FR.ISO8859-1
                br_FR.iso88591           br_FR.ISO8859-1
                br_FR.iso885915@euro     br_FR.ISO8859-15
                br_FR.utf8               br_FR.UTF-8
                br_FR@euro               br_FR.ISO8859-15
                bs_BA                    bs_BA.ISO8859-2
                bs_BA.iso88592           bs_BA.ISO8859-2
                bs_BA.utf8               bs_BA.UTF-8
                ca                       ca_ES.ISO8859-1
                ca_AD                    ca_AD.ISO8859-15
                ca_AD.iso885915          ca_AD.ISO8859-15
                ca_AD.utf8               ca_AD.UTF-8
                ca_ES                    ca_ES.ISO8859-1
                ca_ES.8859-15            ca_ES.ISO8859-15
                ca_ES.8859-15@euro       ca_ES.ISO8859-15
                ca_ES.IBM-1252           ca_ES.ANSI1252
                ca_ES.ISO8859-15@euro    ca_ES.ISO8859-15
                ca_ES.iso88591           ca_ES.ISO8859-1
                ca_ES.utf8               ca_ES.UTF-8
                ca_ES@euro               ca_ES.ISO8859-15
                ca_FR                    ca_FR.ISO8859-15
                ca_FR.iso885915          ca_FR.ISO8859-15
                ca_FR.utf8               ca_FR.UTF-8
                ca_IT                    ca_IT.ISO8859-15
                ca_IT.iso885915          ca_IT.ISO8859-15
                ca_IT.utf8               ca_IT.UTF-8
                cs                       cs_CZ.ISO8859-2
                cs_CZ                    cs_CZ.ISO8859-2
                cs_CZ.iso88592           cs_CZ.ISO8859-2
                cs_CZ.utf8               cs_CZ.UTF-8
                cy_GB                    cy_GB.ISO8859-14
                cy_GB.iso885914          cy_GB.ISO8859-14
                cy_GB.utf8               cy_GB.UTF-8
                da                       da_DK.ISO8859-1
                da.ISO8859-15            da_DK.ISO8859-15
                da_DK                    da_DK.ISO8859-1
                da_DK.8859-15            da_DK.ISO8859-15
                da_DK.iso88591           da_DK.ISO8859-1
                da_DK.iso885915          da_DK.ISO8859-15
                da_DK.iso885915@euro     da_DK.ISO8859-15
                da_DK.utf8               da_DK.UTF-8
                de                       de_DE.ISO8859-1
                de.ISO8859-15            de_DE.ISO8859-15
                de.UTF-8                 de_DE.UTF-8
                de_AT                    de_AT.ISO8859-1
                de_AT.8859-15            de_AT.ISO8859-15
                de_AT.8859-15@euro       de_AT.ISO8859-15
                de_AT.ISO8859-15@euro    de_AT.ISO8859-15
                de_AT.iso88591           de_AT.ISO8859-1
                de_AT.utf8               de_AT.UTF-8
                de_AT@euro               de_AT.ISO8859-15
                de_BE                    de_BE.ISO8859-1
                de_BE.iso88591           de_BE.ISO8859-1
                de_BE.iso885915@euro     de_BE.ISO8859-15
                de_BE.utf8               de_BE.UTF-8
                de_BE@euro               de_BE.ISO8859-15
                de_CH                    de_CH.ISO8859-1
                de_CH.8859-15            de_CH.ISO8859-15
                de_CH.iso88591           de_CH.ISO8859-1
                de_CH.utf8               de_CH.UTF-8
                de_DE                    de_DE.ISO8859-1
                de_DE.8859-15            de_DE.ISO8859-15
                de_DE.8859-15@euro       de_DE.ISO8859-15
                de_DE.IBM-1252           de_DE.ANSI1252
                de_DE.ISO8859-15@euro    de_DE.ISO8859-15
                de_DE.UTF-8@euro         de_DE.UTF-8
                de_DE.iso88591           de_DE.ISO8859-1
                de_DE.utf8               de_DE.UTF-8
                de_DE@euro               de_DE.ISO8859-15
                de_LU                    de_LU.ISO8859-15
                de_LU.8859-15            de_LU.ISO8859-15
                de_LU.8859-15@euro       de_LU.ISO8859-15
                de_LU.iso88591           de_LU.ISO8859-1
                de_LU.iso885915@euro     de_LU.ISO8859-15
                de_LU.utf8               de_LU.UTF-8
                de_LU@euro               de_LU.ISO8859-15
                dz_BT                    dz_BT.UTF-8
                dz_BT.utf8               dz_BT.UTF-8
                el                       el_GR.ISO8859-7
                el.UTF-8                 el_CY.UTF-8
                el.sun_eu_greek          el_GR.ISO8859-7
                el_CY                    el_CY.ISO8859-7
                el_CY.iso88597           el_CY.ISO8859-7
                el_CY.utf8               el_CY.UTF-8
                el_GR                    el_GR.ISO8859-7
                el_GR.ISO8859-7@euro     el_GR.ISO8859-7
                el_GR.iso88597           el_GR.ISO8859-7
                el_GR.utf8               el_GR.UTF-8
                en_AU                    en_AU.ISO8859-1
                en_AU.8859-15            en_AU.ISO8859-15
                en_AU.iso88591           en_AU.ISO8859-1
                en_AU.utf8               en_AU.UTF-8
                en_BE                    en_BE.ISO8859-15
                en_BE.8859-15            en_BE.ISO8859-15
                en_BE.8859-15@euro       en_BE.ISO8859-15
                en_BE@euro               en_BE.ISO8859-15
                en_BW                    en_BW.ISO8859-1
                en_BW.iso88591           en_BW.ISO8859-1
                en_BW.utf8               en_BW.UTF-8
                en_CA                    en_CA.ISO8859-1
                en_CA.8859-15            en_CA.ISO8859-15
                en_CA.iso88591           en_CA.ISO8859-1
                en_CA.utf8               en_CA.UTF-8
                en_DK                    en_DK.ISO8859-1
                en_DK.iso88591           en_DK.ISO8859-1
                en_DK.utf8               en_DK.UTF-8
                en_GB                    en_GB.ISO8859-1
                en_GB.8859-15            en_GB.ISO8859-15
                en_GB.8859-15@euro       en_GB.ISO8859-15
                en_GB.IBM-1252           en_GB.ANSI1252
                en_GB.iso88591           en_GB.ISO8859-1
                en_GB.iso885915          en_GB.ISO8859-15
                en_GB.iso885915@euro     en_GB.ISO8859-15
                en_GB.utf8               en_GB.UTF-8
                en_HK                    en_HK.ISO8859-15
                en_HK.8859-15            en_HK.ISO8859-15
                en_HK.iso88591           en_HK.ISO8859-1
                en_HK.utf8               en_HK.UTF-8
                en_IE                    en_IE.ISO8859-1
                en_IE.8859-15            en_IE.ISO8859-15
                en_IE.8859-15@euro       en_IE.ISO8859-15
                en_IE.ISO8859-15@euro    en_IE.ISO8859-15
                en_IE.iso88591           en_IE.ISO8859-1
                en_IE.utf8               en_IE.UTF-8
                en_IE@euro               en_IE.ISO8859-15
                en_IN                    en_IN.ISO8859-15
                en_IN.8859-15            en_IN.ISO8859-15
                en_IN.utf8               en_IN.UTF-8
                en_NZ                    en_NZ.ISO8859-1
                en_NZ.8859-15            en_NZ.ISO8859-15
                en_NZ.iso88591           en_NZ.ISO8859-1
                en_NZ.utf8               en_NZ.UTF-8
                en_PH                    en_PH.ISO8859-15
                en_PH.8859-15            en_PH.ISO8859-15
                en_PH.iso88591           en_PH.ISO8859-1
                en_PH.utf8               en_PH.UTF-8
                en_SG                    en_SG.ISO8859-15
                en_SG.8859-15            en_SG.ISO8859-15
                en_SG.iso88591           en_SG.ISO8859-1
                en_SG.utf8               en_SG.UTF-8
                en_US                    en_US.ISO8859-1
                en_US.8859-15            en_US.ISO8859-15
                en_US.iso88591           en_US.ISO8859-1
                en_US.iso885915          en_US.ISO8859-15
                en_US.utf8               en_US.UTF-8
                en_ZA                    en_ZA.ISO8859-15
                en_ZA.8859-15            en_ZA.ISO8859-15
                en_ZA.iso88591           en_ZA.ISO8859-1
                en_ZA.utf8               en_ZA.UTF-8
                en_ZW                    en_ZW.ISO8859-1
                en_ZW.iso88591           en_ZW.ISO8859-1
                en_ZW.utf8               en_ZW.UTF-8
                es                       es_ES.ISO8859-1
                es.ISO8859-15            es_ES.ISO8859-15
                es.UTF-8                 es_ES.UTF-8
                es_AR                    es_AR.ISO8859-1
                es_AR.8859-15            es_AR.ISO8859-15
                es_AR.iso88591           es_AR.ISO8859-1
                es_AR.utf8               es_AR.UTF-8
                es_BO                    es_BO.ISO8859-1
                es_BO.8859-15            es_BO.ISO8859-15
                es_BO.iso88591           es_BO.ISO8859-1
                es_BO.utf8               es_BO.UTF-8
                es_CL                    es_CL.ISO8859-1
                es_CL.8859-15            es_CL.ISO8859-15
                es_CL.iso88591           es_CL.ISO8859-1
                es_CL.utf8               es_CL.UTF-8
                es_CO                    es_CO.ISO8859-1
                es_CO.8859-15            es_CO.ISO8859-15
                es_CO.iso88591           es_CO.ISO8859-1
                es_CO.utf8               es_CO.UTF-8
                es_CR                    es_CR.ISO8859-1
                es_CR.8859-15            es_CR.ISO8859-15
                es_CR.iso88591           es_CR.ISO8859-1
                es_CR.utf8               es_CR.UTF-8
                es_DO                    es_DO.ISO8859-15
                es_DO.8859-15            es_DO.ISO8859-15
                es_DO.iso88591           es_DO.ISO8859-1
                es_DO.utf8               es_DO.UTF-8
                es_EC                    es_EC.ISO8859-1
                es_EC.8859-15            es_EC.ISO8859-15
                es_EC.iso88591           es_EC.ISO8859-1
                es_EC.utf8               es_EC.UTF-8
                es_ES                    es_ES.ISO8859-1
                es_ES.8859-15            es_ES.ISO8859-15
                es_ES.8859-15@euro       es_ES.ISO8859-15
                es_ES.IBM-1252           es_ES.ANSI1252
                es_ES.ISO8859-15@euro    es_ES.ISO8859-15
                es_ES.UTF-8@euro         es_ES.UTF-8
                es_ES.iso88591           es_ES.ISO8859-1
                es_ES.utf8               es_ES.UTF-8
                es_ES@euro               es_ES.ISO8859-15
                es_GT                    es_GT.ISO8859-1
                es_GT.8859-15            es_GT.ISO8859-15
                es_GT.iso88591           es_GT.ISO8859-1
                es_GT.utf8               es_GT.UTF-8
                es_HN                    es_HN.ISO8859-15
                es_HN.8859-15            es_HN.ISO8859-15
                es_HN.iso88591           es_HN.ISO8859-1
                es_HN.utf8               es_HN.UTF-8
                es_MX                    es_MX.ISO8859-1
                es_MX.8859-15            es_MX.ISO8859-15
                es_MX.iso88591           es_MX.ISO8859-1
                es_NI.utf8               es_NI.UTF-8
                es_PA                    es_PA.ISO8859-1
                es_PA.8859-15            es_PA.ISO8859-15
                es_PA.iso88591           es_PA.ISO8859-1
                es_PA.utf8               es_PA.UTF-8
                es_PE                    es_PE.ISO8859-1
                es_PE.8859-15            es_PE.ISO8859-15
                es_PE.iso88591           es_PE.ISO8859-1
                es_PE.utf8               es_PE.UTF-8
                es_PR                    es_PR.ISO8859-15
                es_PR.8859-15            es_PR.ISO8859-15
                es_PR.iso88591           es_PR.ISO8859-1
                es_PR.utf8               es_PR.UTF-8
                es_PY                    es_PY.ISO8859-1
                es_PY.8859-15            es_PY.ISO8859-15
                es_PY.iso88591           es_PY.ISO8859-1
                es_PY.utf8               es_PY.UTF-8
                es_SV                    es_SV.ISO8859-1
                es_SV.8859-15            es_SV.ISO8859-15
                es_SV.iso88591           es_SV.ISO8859-1
                es_SV.utf8               es_SV.UTF-8
                es_US                    es_US.ISO8859-15
                es_US.8859-15            es_US.ISO8859-15
                es_US.iso88591           es_US.ISO8859-1
                es_US.utf8               es_US.UTF-8
                es_UY                    es_UY.ISO8859-1
                es_UY.8859-15            es_UY.ISO8859-15
                es_UY.iso88591           es_UY.ISO8859-1
                es_UY.utf8               es_UY.UTF-8
                es_VE                    es_VE.ISO8859-1
                es_VE.8859-15            es_VE.ISO8859-15
                es_VE.iso88591           es_VE.ISO8859-1
                es_VE.utf8               es_VE.UTF-8
                et                       et_EE.ISO8859-15
                et_EE                    et_EE.ISO8859-15
                et_EE.iso88591           et_EE.ISO8859-1
                et_EE.iso885915          et_EE.ISO8859-15
                et_EE.utf8               et_EE.UTF-8
                eu_ES                    eu_ES.ISO8859-1
                eu_ES.iso88591           eu_ES.ISO8859-1
                eu_ES.iso885915@euro     eu_ES.ISO8859-15
                eu_ES.utf8               eu_ES.UTF-8
                eu_ES@euro               eu_ES.ISO8859-15
                fa_IR                    fa_IR.UTF-8
                fa_IR.utf8               fa_IR.UTF-8
                fi                       fi_FI.ISO8859-1
                fi.ISO8859-15            fi_FI.ISO8859-15
                fi_FI                    fi_FI.ISO8859-1
                fi_FI.8859-15            fi_FI.ISO8859-15
                fi_FI.8859-15@euro       fi_FI.ISO8859-15
                fi_FI.IBM-1252           fi_FI.ANSI1252
                fi_FI.ISO8859-15@euro    fi_FI.ISO8859-15
                fi_FI.iso88591           fi_FI.ISO8859-1
                fi_FI.utf8               fi_FI.UTF-8
                fi_FI@euro               fi_FI.ISO8859-15
                fo_FO                    fo_FO.ISO8859-1
                fo_FO.iso88591           fo_FO.ISO8859-1
                fo_FO.utf8               fo_FO.UTF-8
                fr                       fr_FR.ISO8859-1
                fr.ISO8859-15            fr_FR.ISO8859-15
                fr.UTF-8                 fr_FR.UTF-8
                fr_BE                    fr_BE.ISO8859-1
                fr_BE.8859-15            fr_BE.ISO8859-15
                fr_BE.8859-15@euro       fr_BE.ISO8859-15
                fr_BE.IBM-1252           fr_BE.ANSI1252
                fr_BE.ISO8859-15@euro    fr_BE.ISO8859-15
                fr_BE.UTF-8@euro         fr_BE.UTF-8
                fr_BE.iso88591           fr_BE.ISO8859-1
                fr_BE.utf8               fr_BE.UTF-8
                fr_BE@euro               fr_BE.ISO8859-15
                fr_CA                    fr_CA.ISO8859-1
                fr_CA.8859-15            fr_CA.ISO8859-15
                fr_CA.iso88591           fr_CA.ISO8859-1
                fr_CA.utf8               fr_CA.UTF-8
                fr_CH                    fr_CH.ISO8859-1
                fr_CH.8859-15            fr_CH.ISO8859-15
                fr_CH.iso88591           fr_CH.ISO8859-1
                fr_CH.utf8               fr_CH.UTF-8
                fr_FR                    fr_FR.ISO8859-1
                fr_FR.8859-15            fr_FR.ISO8859-15
                fr_FR.8859-15@euro       fr_FR.ISO8859-15
                fr_FR.IBM-1252           fr_FR.ANSI1252
                fr_FR.ISO8859-15@euro    fr_FR.ISO8859-15
                fr_FR.UTF-8@euro         fr_FR.UTF-8
                fr_FR.iso88591           fr_FR.ISO8859-1
                fr_FR.utf8               fr_FR.UTF-8
                fr_FR@euro               fr_FR.ISO8859-15
                fr_LU                    fr_LU.ISO8859-15
                fr_LU.8859-15            fr_LU.ISO8859-15
                fr_LU.8859-15@euro       fr_LU.ISO8859-15
                fr_LU.iso88591           fr_LU.ISO8859-1
                fr_LU.iso885915@euro     fr_LU.ISO8859-15
                fr_LU.utf8               fr_LU.UTF-8
                fr_LU@euro               fr_LU.ISO8859-15
                fy_NL                    fy_NL.UTF-8
                fy_NL.utf8               fy_NL.UTF-8
                ga_IE                    ga_IE.ISO8859-1
                ga_IE.iso88591           ga_IE.ISO8859-1
                ga_IE.iso885915@euro     ga_IE.ISO8859-15
                ga_IE.utf8               ga_IE.UTF-8
                ga_IE@euro               ga_IE.ISO8859-15
                gd_GB                    gd_GB.ISO8859-15
                gd_GB.iso885915          gd_GB.ISO8859-15
                gd_GB.utf8               gd_GB.UTF-8
                gl_ES                    gl_ES.ISO8859-1
                gl_ES.iso88591           gl_ES.ISO8859-1
                gl_ES.iso885915@euro     gl_ES.ISO8859-15
                gl_ES.utf8               gl_ES.UTF-8
                gl_ES@euro               gl_ES.ISO8859-15
                gu_IN                    gu_IN.UTF-8
                gu_IN.utf8               gu_IN.UTF-8
                gv_GB                    gv_GB.ISO8859-1
                gv_GB.iso88591           gv_GB.ISO8859-1
                gv_GB.utf8               gv_GB.UTF-8
                he                       he_IL.ISO8859-8
                he_IL                    he_IL.ISO8859-8
                he_IL.iso88598           he_IL.ISO8859-8
                he_IL.utf8               he_IL.UTF-8
                hi_IN                    hi_IN.UTF-8
                hi_IN.utf8               hi_IN.UTF-8
                hr_HR                    hr_HR.ISO8859-2
                hr_HR.iso88592           hr_HR.ISO8859-2
                hr_HR.utf8               hr_HR.UTF-8
                hu                       hu_HU.ISO8859-2
                hu_HU                    hu_HU.ISO8859-2
                hu_HU.iso88592           hu_HU.ISO8859-2
                hu_HU.utf8               hu_HU.UTF-8
                hy_AM                    hy_AM.UTF-8
                hy_AM.utf8               hy_AM.UTF-8
                id_ID                    id_ID.ISO8859-15
                id_ID.8859-15            id_ID.ISO8859-15
                id_ID.iso88591           id_ID.ISO8859-1
                id_ID.utf8               id_ID.UTF-8
                is_IS                    is_IS.ISO8859-1
                is_IS.8859-15            is_IS.ISO8859-15
                is_IS.iso88591           is_IS.ISO8859-1
                is_IS.utf8               is_IS.UTF-8
                it                       it_IT.ISO8859-1
                it.ISO8859-15            it_IT.ISO8859-15
                it.UTF-8                 it_IT.UTF-8
                it_CH                    it_CH.ISO8859-15
                it_CH.8859-15            it_CH.ISO8859-15
                it_CH.iso88591           it_CH.ISO8859-1
                it_CH.utf8               it_CH.UTF-8
                it_IT                    it_IT.ISO8859-1
                it_IT.8859-15            it_IT.ISO8859-15
                it_IT.8859-15@euro       it_IT.ISO8859-15
                it_IT.IBM-1252           it_IT.ANSI1252
                it_IT.ISO8859-15@euro    it_IT.ISO8859-15
                it_IT.UTF-8@euro         it_IT.UTF-8
                it_IT.iso88591           it_IT.ISO8859-1
                it_IT.utf8               it_IT.UTF-8
                it_IT@euro               it_IT.ISO8859-15
                iw_IL                    iw_IL.ISO8859-8
                iw_IL.iso88598           iw_IL.ISO8859-8
                iw_IL.utf8               iw_IL.UTF-8
                ja                       ja_JP.eucJP
                ja_JP                    ja_JP.eucJP
                ja_JP.IBM-eucJP          ja_JP.eucJP
                ja_JP.eucjp              ja_JP.eucJP
                ja_JP.utf8               ja_JP.UTF-8
                ka_GE.utf8               ka_GE.UTF-8
                kk_KZ.utf8               kk_KZ.UTF-8
                kl_GL                    kl_GL.ISO8859-1
                kl_GL.iso88591           kl_GL.ISO8859-1
                kl_GL.utf8               kl_GL.UTF-8
                km_KH                    km_KH.UTF-8
                km_KH.utf8               km_KH.UTF-8
                kn_IN                    kn_IN.UTF-8
                kn_IN.utf8               kn_IN.UTF-8
                ko                       ko_KR.EUC
                ko.UTF-8                 ko_KR.UTF-8
                ko_KR                    ko_KR.EUC
                ko_KR.IBM-eucKR          ko_KR.EUC
                ko_KR.euckr              ko_KR.EUC
                ko_KR.utf8               ko_KR.UTF-8
                ku_TR                    ku_TR.ISO8859-9
                ku_TR.iso88599           ku_TR.ISO8859-9
                ku_TR.utf8               ku_TR.UTF-8
                kw_GB                    kw_GB.ISO8859-1
                kw_GB.iso88591           kw_GB.ISO8859-1
                kw_GB.utf8               kw_GB.UTF-8
                ky_KG                    ky_KG.UTF-8
                ky_KG.utf8               ky_KG.UTF-8
                lg_UG.utf8               lg_UG.UTF-8
                lo_LA                    lo_LA.UTF-8
                lo_LA.utf8               lo_LA.UTF-8
                lt                       lt_LT.ISO8859-13
                lt_LT                    lt_LT.ISO8859-13
                lt_LT.iso885913          lt_LT.ISO8859-13
                lt_LT.utf8               lt_LT.UTF-8
                lv                       lv_LV.ISO8859-13
                lv_LV                    lv_LV.ISO8859-13
                lv_LV.iso885913          lv_LV.ISO8859-13
                lv_LV.utf8               lv_LV.UTF-8
                mg_MG                    mg_MG.ISO8859-15
                mg_MG.iso885915          mg_MG.ISO8859-15
                mg_MG.utf8               mg_MG.UTF-8
                mi_NZ                    mi_NZ.ISO8859-13
                mi_NZ.iso885913          mi_NZ.ISO8859-13
                mi_NZ.utf8               mi_NZ.UTF-8
                mk_MK                    mk_MK.ISO8859-5
                mk_MK.iso88595           mk_MK.ISO8859-5
                mk_MK.utf8               mk_MK.UTF-8
                ml_IN                    ml_IN.UTF-8
                ml_IN.utf8               ml_IN.UTF-8
                mn_MN                    mn_MN.UTF-8
                mn_MN.utf8               mn_MN.UTF-8
                mr_IN                    mr_IN.UTF-8
                mr_IN.utf8               mr_IN.UTF-8
                ms_MY                    ms_MY.ISO8859-15
                ms_MY.8859-15            ms_MY.ISO8859-15
                ms_MY.iso88591           ms_MY.ISO8859-1
                ms_MY.utf8               ms_MY.UTF-8
                mt_MT                    mt_MT.ISO8859-3
                mt_MT.iso88593           mt_MT.ISO8859-3
                mt_MT.utf8               mt_MT.UTF-8
                nb_NO                    nb_NO.ISO8859-1
                nb_NO.iso88591           nb_NO.ISO8859-1
                nb_NO.utf8               nb_NO.UTF-8
                ne_NP                    ne_NP.UTF-8
                ne_NP.utf8               ne_NP.UTF-8
                nl                       nl_NL.ISO8859-1
                nl.ISO8859-15            nl_NL.ISO8859-15
                nl_BE                    nl_BE.ISO8859-1
                nl_BE.8859-15            nl_BE.ISO8859-15
                nl_BE.8859-15@euro       nl_BE.ISO8859-15
                nl_BE.IBM-1252           nl_BE.ANSI1252
                nl_BE.ISO8859-15@euro    nl_BE.ISO8859-15
                nl_BE.iso88591           nl_BE.ISO8859-1
                nl_BE.utf8               nl_BE.UTF-8
                nl_BE@euro               nl_BE.ISO8859-15
                nl_NL                    nl_NL.ISO8859-1
                nl_NL.8859-15            nl_NL.ISO8859-15
                nl_NL.8859-15@euro       nl_NL.ISO8859-15
                nl_NL.IBM-1252           nl_NL.ANSI1252
                nl_NL.ISO8859-15@euro    nl_NL.ISO8859-15
                nl_NL.iso88591           nl_NL.ISO8859-1
                nl_NL.utf8               nl_NL.UTF-8
                nl_NL@euro               nl_NL.ISO8859-15
                nn_NO                    nn_NO.ISO8859-1
                nn_NO.iso88591           nn_NO.ISO8859-1
                nn_NO.utf8               nn_NO.UTF-8
                no                       nb_NO.ISO8859-1
                no_NO                    nb_NO.ISO8859-1
                no_NO.8859-15            no_NO.ISO8859-15
                no_NO.ISO8859-1@bokmal   nb_NO.ISO8859-1
                no_NO.ISO8859-1@nynorsk  nn_NO.ISO8859-1
                no_NO.iso88591           no_NO.ISO8859-1
                no_NO.utf8               no_NO.UTF-8
                no_NY                    nn_NO.ISO8859-1
                nr_ZA                    nr_ZA.UTF-8
                nr_ZA.utf8               nr_ZA.UTF-8
                oc_FR                    oc_FR.ISO8859-1
                oc_FR.iso88591           oc_FR.ISO8859-1
                oc_FR.utf8               oc_FR.UTF-8
                om_ET                    om_ET.UTF-8
                om_ET.utf8               om_ET.UTF-8
                om_KE                    om_KE.ISO8859-1
                om_KE.iso88591           om_KE.ISO8859-1
                om_KE.utf8               om_KE.UTF-8
                or_IN                    or_IN.UTF-8
                or_IN.utf8               or_IN.UTF-8
                pa_IN                    pa_IN.UTF-8
                pa_IN.utf8               pa_IN.UTF-8
                pa_PK                    pa_PK.UTF-8
                pa_PK.utf8               pa_PK.UTF-8
                pl                       pl_PL.ISO8859-2
                pl.UTF-8                 pl_PL.UTF-8
                pl_PL                    pl_PL.ISO8859-2
                pl_PL.iso88592           pl_PL.ISO8859-2
                pl_PL.utf8               pl_PL.UTF-8
                pt                       pt_PT.ISO8859-1
                pt.ISO8859-15            pt_PT.ISO8859-15
                pt_BR                    pt_BR.ISO8859-1
                pt_BR.8859-15            pt_BR.ISO8859-15
                pt_BR.iso88591           pt_BR.ISO8859-1
                pt_BR.utf8               pt_BR.UTF-8
                pt_PT                    pt_PT.ISO8859-1
                pt_PT.8859-15            pt_PT.ISO8859-15
                pt_PT.8859-15@euro       pt_PT.ISO8859-15
                pt_PT.IBM-1252           pt_PT.ANSI1252
                pt_PT.ISO8859-15@euro    pt_PT.ISO8859-15
                pt_PT.iso88591           pt_PT.ISO8859-1
                pt_PT.utf8               pt_PT.UTF-8
                pt_PT@euro               pt_PT.ISO8859-15
                ro_RO                    ro_RO.ISO8859-2
                ro_RO.iso88592           ro_RO.ISO8859-2
                ro_RO.utf8               ro_RO.UTF-8
                ru                       ru_RU.ISO8859-5
                ru.UTF-8                 ru_RU.UTF-8
                ru.koi8-r                ru_RU.KOI8-R
                ru_RU                    ru_RU.ISO8859-5
                ru_RU.iso88595           ru_RU.ISO8859-5
                ru_RU.koi8r              ru_RU.KOI8-R
                ru_RU.utf8               ru_RU.UTF-8
                ru_UA                    ru_UA.KOI8-U
                ru_UA.koi8u              ru_UA.KOI8-U
                ru_UA.utf8               ru_UA.UTF-8
                rw_RW                    rw_RW.UTF-8
                rw_RW.utf8               rw_RW.UTF-8
                se_NO                    se_NO.UTF-8
                se_NO.utf8               se_NO.UTF-8
                sh                       bs_BA.ISO8859-2
                sh_BA                    bs_BA.ISO8859-2
                sh_BA.ISO8859-2@bosnia   bs_BA.ISO8859-2
                sh_BA.UTF-8              bs_BA.UTF-8
                sh_SP                    sh_SP.ISO8859-2
                sh_YU                    sh_YU.ISO8859-2
                si_LK                    si_LK.UTF-8
                si_LK.utf8               si_LK.UTF-8
                sk_SK                    sk_SK.ISO8859-2
                sk_SK.iso88592           sk_SK.ISO8859-2
                sk_SK.utf8               sk_SK.UTF-8
                sl_SI                    sl_SI.ISO8859-2
                sl_SI.iso88592           sl_SI.ISO8859-2
                sl_SI.utf8               sl_SI.UTF-8
                so_DJ                    so_DJ.ISO8859-1
                so_DJ.iso88591           so_DJ.ISO8859-1
                so_DJ.utf8               so_DJ.UTF-8
                so_ET                    so_ET.UTF-8
                so_ET.utf8               so_ET.UTF-8
                so_KE                    so_KE.ISO8859-1
                so_KE.iso88591           so_KE.ISO8859-1
                so_KE.utf8               so_KE.UTF-8
                so_SO                    so_SO.ISO8859-1
                so_SO.iso88591           so_SO.ISO8859-1
                so_SO.utf8               so_SO.UTF-8
                sq_AL                    sq_AL.ISO8859-2
                sq_AL.8859-15            sq_AL.ISO8859-15
                sq_AL.iso88591           sq_AL.ISO8859-1
                sq_AL.utf8               sq_AL.UTF-8
                sr_CS                    sr_RS.UTF-8
                sr_CS.UTF-8              sr_RS.UTF-8
                sr_CS.iso88595           sr_CS.ISO8859-5
                sr_ME                    sr_ME.UTF-8
                sr_ME.utf8               sr_ME.UTF-8
                sr_RS                    sr_RS.UTF-8
                sr_RS.utf8               sr_RS.UTF-8
                sr_SP                    sr_RS.ISO8859-5
                sr_YU                    sr_RS.ISO8859-5
                sr_YU.ISO8859-5          sr_RS.ISO8859-5
                ss_ZA                    ss_ZA.UTF-8
                ss_ZA.utf8               ss_ZA.UTF-8
                st_ZA                    st_ZA.ISO8859-1
                st_ZA.iso88591           st_ZA.ISO8859-1
                st_ZA.utf8               st_ZA.UTF-8
                sv                       sv_SE.ISO8859-1
                sv.ISO8859-15            sv_SE.ISO8859-15
                sv.UTF-8                 sv_SE.UTF-8
                sv_FI                    sv_FI.ISO8859-1
                sv_FI.iso88591           sv_FI.ISO8859-1
                sv_FI.iso885915@euro     sv_FI.ISO8859-15
                sv_FI.utf8               sv_FI.UTF-8
                sv_FI@euro               sv_FI.ISO8859-15
                sv_SE                    sv_SE.ISO8859-1
                sv_SE.8859-15            sv_SE.ISO8859-15
                sv_SE.iso88591           sv_SE.ISO8859-1
                sv_SE.iso885915          sv_SE.ISO8859-15
                sv_SE.iso885915@euro     sv_SE.ISO8859-15
                sv_SE.utf8               sv_SE.UTF-8
                ta_IN                    ta_IN.UTF-8
                ta_IN.utf8               ta_IN.UTF-8
                te_IN                    te_IN.UTF-8
                te_IN.utf8               te_IN.UTF-8
                tg_TJ                    tg_TJ.KOI8-T
                tg_TJ.koi8t              tg_TJ.KOI8-T
                tg_TJ.utf8               tg_TJ.UTF-8
                th                       th_TH.TIS620
                th_TH                    th_TH.TIS620
                th_TH.ISO8859-11         th_TH.TIS620
                th_TH.TIS-620            th_TH.TIS620
                th_TH.utf8               th_TH.UTF-8
                ti_ER                    ti_ER.UTF-8
                ti_ER.utf8               ti_ER.UTF-8
                ti_ET                    ti_ET.UTF-8
                ti_ET.utf8               ti_ET.UTF-8
                tl_PH                    tl_PH.ISO8859-1
                tl_PH.iso88591           tl_PH.ISO8859-1
                tl_PH.utf8               tl_PH.UTF-8
                tn_ZA                    tn_ZA.UTF-8
                tn_ZA.utf8               tn_ZA.UTF-8
                tr                       tr_TR.ISO8859-9
                tr_CY                    tr_CY.ISO8859-9
                tr_CY.iso88599           tr_CY.ISO8859-9
                tr_CY.utf8               tr_CY.UTF-8
                tr_TR                    tr_TR.ISO8859-9
                tr_TR.iso88599           tr_TR.ISO8859-9
                tr_TR.utf8               tr_TR.UTF-8
                ts_ZA                    ts_ZA.UTF-8
                ts_ZA.utf8               ts_ZA.UTF-8
                tt_RU.utf8               tt_RU.UTF-8
                uk_UA                    uk_UA.KOI8-U
                uk_UA.koi8u              uk_UA.KOI8-U
                uk_UA.utf8               uk_UA.UTF-8
                ur_PK                    ur_PK.UTF-8
                ur_PK.utf8               ur_PK.UTF-8
                uz_UZ                    uz_UZ.ISO8859-1
                uz_UZ.iso88591           uz_UZ.ISO8859-1
                ve_ZA                    ve_ZA.UTF-8
                ve_ZA.utf8               ve_ZA.UTF-8
                vi_VN                    vi_VN.UTF-8
                vi_VN.tcvn               vi_VN.TCVN5712-1
                vi_VN.utf8               vi_VN.UTF-8
                wa_BE                    wa_BE.ISO8859-1
                wa_BE.iso88591           wa_BE.ISO8859-1
                wa_BE.iso885915@euro     wa_BE.ISO8859-15
                wa_BE.utf8               wa_BE.UTF-8
                wa_BE@euro               wa_BE.ISO8859-15
                xh_ZA                    xh_ZA.ISO8859-1
                xh_ZA.iso88591           xh_ZA.ISO8859-1
                xh_ZA.utf8               xh_ZA.UTF-8
                yi_US                    yi_US.ANSI1255
                yi_US.cp1255             yi_US.ANSI1255
                yi_US.utf8               yi_US.UTF-8
                zh                       zh_CN.EUC
                zh.GBK                   zh_CN.GBK
                zh.UTF-8                 zh_CN.UTF-8
                zh_CN                    zh_CN.EUC
                zh_CN.IBM-eucCN          zh_CN.EUC
                zh_CN.gb18030            zh_CN.GB18030
                zh_CN.gb2312             zh_CN.EUC
                zh_CN.gbk                zh_CN.GBK
                zh_CN.utf8               zh_CN.UTF-8
                zh_HK                    zh_HK.BIG5HK
                zh_HK.big5hkscs          zh_HK.BIG5HK
                zh_HK.utf8               zh_HK.UTF-8
                zh_SG                    zh_SG.EUC
                zh_SG.gb2312             zh_SG.EUC
                zh_SG.gbk                zh_SG.GBK
                zh_SG.utf8               zh_SG.UTF-8
                zh_TW                    zh_TW.EUC
                zh_TW.IBM-eucTW          zh_TW.EUC
                zh_TW.big5               zh_TW.BIG5
                zh_TW.euctw              zh_TW.EUC
                zh_TW.utf8               zh_TW.UTF-8
                zu_ZA                    zu_ZA.ISO8859-1
                zu_ZA.iso88591           zu_ZA.ISO8859-1
                zu_ZA.utf8               zu_ZA.UTF-8
.fi
.in -2
.sp

.RE
.RS +4
.TP
2.
Obsoleted Solaris locale names that are additionally checked against to find message object or message catalog files asspecified in \fBgettext\fR(1), \fBcatopen\fR(3C), and \fBgettext\fR(3C)
.sp
When the current locale is one of the listed canonical locales and there is no matching message object or message catalog file for the current running program to open with using the current locale name, the messaging functions additionally check on the existence of the message object or the message catalog file to open by utilizing the additional locale names shown at below as aliases:
.sp
.in +2
.nf
 
Canonical Locale Name    Additional Locale Names Checked
---------------------    -------------------------------
ar_EG.ISO8859-6          ar
bg_BG.ISO8859-5          bg_BG
bs_BA.ISO8859-2          sh, sh_BA, sh_BA.ISO8859-2@bosnia
bs_BA.UTF-8              sh_BA.UTF-8
ca_ES.ISO8859-1          ca, ca_ES
ca_ES.ISO8859-15         ca_ES.ISO8859-15@euro
cs_CZ.ISO8859-2          cs, cs_CZ
da_DK.ISO8859-1          da, da_DK
da_DK.ISO8859-15         da.ISO8859-15
de_AT.ISO8859-1          de_AT
de_AT.ISO8859-15         de_AT.ISO8859-15@euro
de_CH.ISO8859-1          de_CH
de_DE.ISO8859-1          de, de_DE
de_DE.ISO8859-15         de.ISO8859-15, de_DE.ISO8859-15@euro
de_DE.UTF-8              de.UTF-8, de_DE.UTF-8@euro
el_CY.UTF-8              el.UTF-8
el_GR.ISO8859-7          el, el.sun_eu_greek, el_GR,
                         el_GR.ISO8859-7@euro
en_AU.ISO8859-1          en_AU
en_CA.ISO8859-1          en_CA
en_GB.ISO8859-1          en_GB
en_IE.ISO8859-1          en_IE
en_IE.ISO8859-15         en_IE.ISO8859-15@euro
en_NZ.ISO8859-1          en_NZ
en_US.ISO8859-1          en_US
es_AR.ISO8859-1          es_AR
es_BO.ISO8859-1          es_BO
es_CL.ISO8859-1          es_CL
es_CO.ISO8859-1          es_CO
es_CR.ISO8859-1          es_CR
es_EC.ISO8859-1          es_EC
es_ES.ISO8859-1          es, es_ES
es_ES.ISO8859-15         es.ISO8859-15, es_ES.ISO8859-15@euro
es_ES.UTF-8              es.UTF-8, es_ES.UTF-8@euro
es_GT.ISO8859-1          es_GT
es_MX.ISO8859-1          es_MX
es_NI.ISO8859-1          es_NI
es_PA.ISO8859-1          es_PA
es_PE.ISO8859-1          es_PE
es_PY.ISO8859-1          es_PY
es_SV.ISO8859-1          es_SV
es_UY.ISO8859-1          es_UY
es_VE.ISO8859-1          es_VE
et_EE.ISO8859-15         et, et_EE
fi_FI.ISO8859-1          fi, fi_FI
fi_FI.ISO8859-15         fi.ISO8859-15, fi_FI.ISO8859-15@euro
fr_BE.ISO8859-1          fr_BE
fr_BE.ISO8859-15         fr_BE.ISO8859-15@euro
fr_BE.UTF-8              fr_BE.UTF-8@euro
fr_CA.ISO8859-1          fr_CA
fr_CH.ISO8859-1          fr_CH
fr_FR.ISO8859-1          fr, fr_FR
fr_FR.ISO8859-15         fr.ISO8859-15, fr_FR.ISO8859-15@euro
fr_FR.UTF-8              fr.UTF-8, fr_FR.UTF-8@euro
he_IL.ISO8859-8          he, he_IL
hr_HR.ISO8859-2          hr_HR
hu_HU.ISO8859-2          hu, hu_HU
is_IS.ISO8859-1          is_IS
it_IT.ISO8859-1          it, it_IT
it_IT.ISO8859-15         it.ISO8859-15, it_IT.ISO8859-15@euro
it_IT.UTF-8              it.UTF-8, it_IT.UTF-8@euro
ja_JP.eucJP              ja
ko_KR.EUC                ko
ko_KR.UTF-8              ko.UTF-8
lt_LT.ISO8859-13         lt, lt_LT
lv_LV.ISO8859-13         lv, lv_LV
mk_MK.ISO8859-5          mk_MK
nb_NO.ISO8859-1          no, no_NO, no_NO.ISO8859-1@bokmal
nl_BE.ISO8859-1          nl_BE
nl_BE.ISO8859-15         nl_BE.ISO8859-15@euro
nl_NL.ISO8859-1          nl, nl_NL
nl_NL.ISO8859-15         nl.ISO8859-15, nl_NL.ISO8859-15@euro
nn_NO.ISO8859-1          no_NO.ISO8859-1@nynorsk, no_NY
pl_PL.ISO8859-2          pl, pl_PL
pl_PL.UTF-8              pl.UTF-8
pt_BR.ISO8859-1          pt_BR
pt_PT.ISO8859-1          pt, pt_PT
pt_PT.ISO8859-15         pt.ISO8859-15, pt_PT.ISO8859-15@euro
ro_RO.ISO8859-2          ro_RO
ru_RU.ISO8859-5          ru, ru_RU
ru_RU.KOI8-R             ru.koi8-r
ru_RU.UTF-8              ru.UTF-8
sk_SK.ISO8859-2          sk_SK
sl_SI.ISO8859-2          sl_SI
sq_AL.ISO8859-2          sq_AL
sr_ME.ISO8859-5          sr_SP, sr_YU, sr_YU.ISO8859-5
sr_ME.UTF-8              sr_CS, sr_CS.UTF-8
sr_RS.ISO8859-5          sr_SP, sr_YU, sr_YU.ISO8859-5
sr_RS.UTF-8              sr_CS, sr_CS.UTF-8
sv_SE.ISO8859-1          sv, sv_SE
sv_SE.ISO8859-15         sv.ISO8859-15
sv_SE.UTF-8              sv.UTF-8
th_TH.TIS620             th, th_TH, th_TH.ISO8859-11
tr_TR.ISO8859-9          tr, tr_TR
zh_CN.EUC                zh
zh_CN.GBK                zh.GBK
zh_CN.UTF-8              zh.UTF-8
zh_TW.EUC                zh_TW
.fi
.in -2
.sp

.RE
.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Interface StabilityCommitted
.TE

.SH SEE ALSO
.sp
.LP
\fBgettext\fR(1), \fBcatopen\fR(3C), \fBgettext\fR(3C), \fBsetlocale\fR(3C), \fBattributes\fR(5), \fBenviron\fR(5)
