#
# Copyright (c) 2003, 2011, Oracle and/or its affiliates. All rights reserved.
#
# lib/libsasl/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.lib.64

install: stubinstall all $(ROOTLIBS64) $(ROOTLINKS64)

stubinstall: stub $(STUBROOTLIBS64) $(STUBROOTLINKS64)
