#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
#

. /lib/svc/share/smf_include.sh
. /lib/svc/share/ipf_include.sh

PIDFILE=$SMF_SYSVOL_FS/ipmon.pid

zone=`smf_zonename`
if [ -f $PIDFILE ] ; then
        pid=`cat $PIDFILE 2>/dev/null`
else
        pid=`pgrep -z $zone ipmon`
fi

case "$1" in
        start)
                /usr/sbin/ipmon -Ds
                ;;

        stop)
                kill -s SIGTERM $pid

                ;;

        *)
                echo "Usage: $0 \c" >&2
                echo "(start|stop)" >&2
                exit 1
                ;;

esac
exit $SMF_EXIT_OK

