#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"

SUBDIRS = authamd gcpu mtst opteron genintel

include ../../Makefile.subdirs
