#
# Copyright (c) 2004, 2011, Oracle and/or its affiliates. All rights reserved.
#

include ../Makefile.com
include ../../Makefile.lib.64

install: stubinstall all $(ROOTLIBS64) $(ROOTLINKS64)

stubinstall: stub $(STUBROOTLIBS64) $(STUBROOTLINKS64)
