#!/usr/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 1994, 2011, Oracle and/or its affiliates. All rights reserved.
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#

# This file loads keyboard mappings and initializes keyboard defaults

. /lib/svc/share/smf_include.sh

smf_assert_globalzone

PROP_LAYOUT="keymap/layout"
DEFAULT_LAYOUT="US-English"

setproparg() {
	/usr/sbin/svccfg -s $SMF_FMRI setprop $1=$2
	/usr/sbin/svcadm refresh $SMF_FMRI
}

case "$1" in
'start')
	#
	# Systems with no hardware keyboard ID may provide an eeprom value,
	# or the value can be supplied in svc:/system/keymap:default. A value
	# supplied in svc:/system/keymap:default will override the value
	# supplied in eeprom.
	#
	[ -x /usr/lib/set_keyboard_layout ] && /usr/lib/set_keyboard_layout

	# Initialize the keyboard defaults
	[ -h /dev/kbd -a -x /usr/bin/kbd ] && /usr/bin/kbd -i >/dev/null 2>&1

	# Load the keymap for the attached keyboard.
	/usr/bin/loadkeys
	;;
'unconfigure')
	setproparg $PROP_LAYOUT $DEFAULT_LAYOUT

	# Set default layout to kernel
	[ -x /usr/bin/kbd ] && /usr/bin/kbd -s $DEFAULT_LAYOUT

	# Re-load the keymap
	/usr/bin/loadkeys
	;;
*)
	echo "Usage: $0 {start | unconfigure}"
	;;
esac

exit $SMF_EXIT_OK
