'\" te
.\" Copyright (c) 1992, X/Open Company Limited All Rights Reserved
.\" Portions Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
.\" Portions Copyright (c) 1982-2007 AT&T Knowledge Ventures
.\" Sun Microsystems, Inc. gratefully acknowledges The Open Group for permission to reproduce portions of its copyrighted documentation. Original documentation from The Open Group can be obtained online at  http://www.opengroup.org/bookstore/.
.\" The Institute of Electrical and Electronics Engineers and The Open Group, have given us permission to reprint portions of their documentation. In the following statement, the phrase "this text" refers to portions of the system documentation. Portions of this text are reprinted and reproduced in electronic form in the Sun OS Reference Manual, from IEEE Std 1003.1, 2004 Edition, Standard for Information Technology -- Portable Operating System Interface (POSIX), The Open Group Base Specifications Issue 6, Copyright (C) 2001-2004 by the Institute of Electrical and Electronics Engineers, Inc and The Open Group. In the event of any discrepancy between these versions and the original IEEE and The Open Group Standard, the original IEEE and The Open Group Standard is the referee document. The original Standard can be obtained online at http://www.opengroup.org/unix/online.html.  This notice shall appear on any product containing this material.
.TH getconf 1 "27 Jul 2011" "SunOS 5.11" "User Commands"
.SH NAME
getconf \- get configuration values
.SH SYNOPSIS
.LP
.nf
\fB/usr/bin/getconf\fR [\fB-v\fR \fIspecification\fR] \fIsystem_var\fR
.fi

.LP
.nf
\fB/usr/bin/getconf\fR [\fB-v\fR \fIspecification\fR] \fIpath_var\fR \fIpathname\fR
.fi

.LP
.nf
\fB/usr/bin/getconf\fR \fB-a\fR
.fi

.LP
.nf
\fB/usr/xpg4/bin/getconf\fR [\fB-v\fR \fIspecification\fR] \fIsystem_var\fR
.fi

.LP
.nf
\fB/usr/xpg4/bin/getconf\fR [\fB-v\fR \fIspecification\fR] \fIpath_var\fR \fIpathname\fR
.fi

.LP
.nf
\fB/usr/xpg4/bin/getconf\fR \fB-a\fR
.fi

.LP
.nf
\fB/usr/xpg6/bin/getconf\fR [\fB-v\fR \fIspecification\fR] \fIsystem_var\fR
.fi

.LP
.nf
\fB/usr/xpg6/bin/getconf\fR [\fB-v\fR \fIspecification\fR] \fIpath_var\fR \fIpathname\fR
.fi

.LP
.nf
\fB/usr/xpg6/bin/getconf\fR \fB-a\fR
.fi

.SH DESCRIPTION
.sp
.LP
In the first synopsis form, the \fBgetconf\fR utility writes to the standard output the value of the variable specified by \fIsystem_var\fR, in accordance with \fIspecification\fR if the \fB-v\fR option is used.
.sp
.LP
In the second synopsis form, \fBgetconf\fR writes to the standard output the value of the variable specified by \fIpath_var\fR for the path specified by \fIpathname\fR, in accordance with \fIspecification\fR if the \fB-v\fR option is used.
.sp
.LP
In the third synopsis form, \fBconfig\fR writes to the standard output the names of the current system configuration variables.
.sp
.LP
The value of each configuration variable is determined as if it were obtained by calling the function from which it is defined to be available. The value reflects conditions in the current operating environment.
.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-a\fR\fR
.ad
.RS 20n
.rt  
Writes the names of the current system configuration variables to the standard output.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR \fIspecification\fR\fR
.ad
.RS 20n
.rt  
Gives the specification which governs the selection of values for configuration variables.
.RE

.SH OPERANDS
.sp
.LP
The following operands are supported:
.sp
.ne 2
.mk
.na
\fB\fIpath_var\fR\fR
.ad
.RS 12n
.rt  
A name of a configuration variable whose value is available from the \fBpathconf\fR(2) function. All of the values in the following table are supported:
.RE

.sp

.sp
.TS
tab();
lw(1.83i) lw(1.83i) lw(1.83i) 
lw(1.83i) lw(1.83i) lw(1.83i) 
.
LINK_MAXNAME_MAX_POSIX_CHOWN_RESTRICTED
MAX_CANONPATH_MAX_POSIX_NO_TRUNC
MAX_INPUTPIPE_BUF_POSIX_VDISABLE
.TE

.sp
.ne 2
.mk
.na
\fB\fIpathname\fR\fR
.ad
.RS 14n
.rt  
A path name for which the variable specified by \fIpath_var\fR is to be determined.
.RE

.sp
.ne 2
.mk
.na
\fB\fIsystem_var\fR\fR
.ad
.RS 14n
.rt  
A name of a configuration variable whose value is available from \fBconfstr\fR(3C) or \fBsysconf\fR(3C). All of the values in the following table are supported:
.RE

.sp

.sp
.TS
tab();
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
ARG_MAXBC_BASE_MAX
BC_DIM_MAXBC_SCALE_MAX
BC_STRING_MAXCHAR_BIT
CHARCLASS_NAME_MAXCHAR_MAX
CHAR_MINCHILD_MAX
CLK_TCKCOLL_WEIGHTS_MAX
CS_PATHEXPR_NEST_MAX
HOST_NAME_MAXINT_MAX
INT_MINLFS64_CFLAGS
LFS64_LDFLAGSLFS64_LIBS
LFS64_LINTFLAGSLFS_CFLAGS
LFS_LDFLAGSLFS_LIBS
LFS_LINTFLAGSLINE_MAX
LONG_BITLONG_MAX
LONG_MINMB_LEN_MAX
NGROUPS_MAXNL_ARGMAX
NL_LANGMAXNL_MSGMAX
NL_NMAXNL_SETMAX
NL_TEXTMAXNZERO
OPEN_MAXPOSIX2_BC_BASE_MAX
POSIX2_BC_DIM_MAXPOSIX2_BC_SCALE_MAX
POSIX2_BC_STRING_MAXPOSIX2_C_BIND
POSIX2_C_DEVPOSIX2_CHAR_TERM
POSIX2_COLL_WEIGHTS_MAXPOSIX2_C_VERSION
POSIX2_EXPR_NEST_MAXPOSIX2_FORT_DEV
POSIX2_FORT_RUNPOSIX2_LINE_MAX
POSIX2_LOCALEDEFPOSIX2_RE_DUP_MAX
POSIX2_SW_DEVPOSIX2_SYMLINKS
POSIX2_UPEPOSIX2_VERSION
POSIX_ALLOC_SIZE_MINPOSIX_REC_INCR_XFER_SIZE
POSIX_REC_MAX_XFER_SIZEPOSIX_REC_MIN_XFER_SIZE
POSIX_REC_XFER_ALIGNPOSIX_V6_ILP32_OFF32
POSIX_V6_ILP32_OFF32_CFLAGSPOSIX_V6_ILP32_OFF32_LDFLAGS
POSIX_V6_ILP32_OFF32_LIBSPOSIX_V6_ILP32_OFFBIG
POSIX_V6_ILP32_OFFBIG_CFLAGSPOSIX_V6_ILP32_OFFBIG_LDFLAGS
POSIX_V6_ILP32_OFFBIG_LIBSPOSIX_V6_LP64_OFF64
POSIX_V6_LP64_OFF64_CFLAGSPOSIX_V6_LP64_OFF64_LDFLAGS
POSIX_V6_LP64_OFF64_LIBSPOSIX_V6_LPBIG_OFFBIG
POSIX_V6_LPBIG_OFFBIG_CFLAGSPOSIX_V6_LPBIG_OFFBIG_LDFLAGS
POSIX_V6_LPBIG_OFFBIG_LIBSPOSIX_V6_WIDTH_RESTRICTED_ENVS
SYMLINK_MAXSYMLOOP_MAX
_POSIX2_BC_BASE_MAX_POSIX2_BC_DIM_MAX
_POSIX2_BC_SCALE_MAX_POSIX2_BC_STRING_MAX
_POSIX2_CHARCLASS_NAME_MAX_POSIX2_CHAR_TERM
_POSIX2_COLL_WEIGHTS_MAX_POSIX2_C_BIND
_POSIX2_C_DEV_POSIX2_C_VERSION
_POSIX2_EXPR_NEST_MAX_POSIX2_FORT_DEV
_POSIX2_FORT_RUN_POSIX2_LINE_MAX
_POSIX2_LOCALEDEF_POSIX2_PBS
_POSIX2_PBS_ACCOUNTING_POSIX2_PBS_CHECKPOINT
_POSIX2_PBS_LOCATE_POSIX2_PBS_MESSAGE
_POSIX2_PBS_TRACK_POSIX2_RE_DUP_MAX
_POSIX2_SW_DEV_POSIX2_UPE
_POSIX2_VERSION_POSIX_ADVISORY_INFO
_POSIX_AIO_LISTIO_MAX_POSIX_AIO_MAX
_POSIX_ARG_MAX_POSIX_ASYNC_IO
_POSIX_BARRIERS_POSIX_CHILD_MAX
_POSIX_CLOCKRES_MIN_POSIX_CLOCK_SELECTION
_POSIX_CPUTIME_POSIX_DELAYTIMER_MAX
_POSIX_HOST_NAME_MAX_POSIX_IPV6
_POSIX_JOB_CONTROL_POSIX_LINK_MAX
_POSIX_LOGIN_NAME_MAX_POSIX_MAX_CANON
_POSIX_MAX_INPUT_POSIX_MONOTONIC_CLOCK
_POSIX_MQ_OPEN_MAX_POSIX_MQ_PRIO_MAX
_POSIX_NAME_MAX_POSIX_NGROUPS_MAX
_POSIX_OPEN_MAX_POSIX_PATH_MAX
_POSIX_PIPE_BUF_POSIX_PRIO_IO
_POSIX_RAW_SOCKETS_POSIX_READER_WRITER_LOCKS
_POSIX_REGEXP_POSIX_RE_DUP_MAX
_POSIX_RTSIG_MAX_POSIX_SAVED_IDS
_POSIX_SEM_NSEMS_MAX_POSIX_SEM_VALUE_MAX
_POSIX_SHELL_POSIX_SIGQUEUE_MAX
_POSIX_SPAWN_POSIX_SPIN_LOCKS
_POSIX_SPORADIC_SERVER_POSIX_SSIZE_MAX
_POSIX_SS_REPL_MAX_POSIX_STREAM_MAX
_POSIX_SYMLINK_MAX_POSIX_SYMLOOP_MAX
_POSIX_SYNC_IO_POSIX_THREAD_ATTR_STACKADDR
_POSIX_THREAD_ATTR_STACKSIZE_POSIX_THREAD_CPUTIME
_POSIX_THREAD_DESTRUCTOR_ITERATIONS_POSIX_THREAD_KEYS_MAX
_POSIX_THREAD_PRIORITY_SCHEDULING_POSIX_THREAD_PRIO_INHERIT
_POSIX_THREAD_PRIO_PROTECT_POSIX_THREAD_PROCESS_SHARED
_POSIX_THREAD_SAFE_FUNCTIONS_POSIX_THREAD_SPORADIC_SERVER
_POSIX_THREAD_THREADS_MAX_POSIX_TIMEOUTS
_POSIX_TIMER_MAX_POSIX_TRA_POSIX_TIMER_MAXCE
_POSIX_TIMESTAMP_RESOLUTION
_POSIX_TRACE_EVENT_FILTER_POSIX_TRACE_EVENT_NAME_MAX
_POSIX_TRACE_INHERIT_POSIX_TRACE_LOG
_POSIX_TRACE_NAME_MAX_POSIX_TRACE_SYS_MAX
_POSIX_TRACE_USER_EVENT_MAX_POSIX_TTY_NAME_MAX
_POSIX_TYPED_MEMORY_OBJECTS_POSIX_TZNAME_MAX
_POSIX_VERSION_POSIX_V6_ILP32_OFF32
_POSIX_V6_ILP32_OFFBIG_POSIX_V6_LP64_OFF64
_POSIX_V6_LPBIG_OFFBIG_V6_ILP32_OFF32
_V6_ILP32_OFFBIG_V6_LP64_OFF64
_V6_LPBIG_OFFBIGRE_DUP_MAX
SCHAR_MAXSCHAR_MIN
SHRT_MAXSHRT_MIN
SSIZE_MAXSTREAM_MAX
TMP_MAXTZNAME_MAX
UCHAR_MAXUINT_MAX
ULONG_MAXUSHRT_MAX
WORD_BITXBS5_ILP32_OFF32
XBS5_ILP32_OFF32_CFLAGSXBS5_ILP32_OFF32_LDFLAGS
XBS5_ILP32_OFF32_LIBSXBS5_ILP32_OFF32_LINTFLAGS
XBS5_ILP32_OFFBIGXBS5_ILP32_OFFBIG_CFLAGS
XBS5_ILP32_OFFBIG_LDFLAGSXBS5_ILP32_OFFBIG_LIBS
XBS5_ILP32_OFFBIG_LINTFLAGSXBS5_LP64_OFF64
XBS5_LP64_OFF64_CFLAGSXBS5_LP64_OFF64_LDFLAGS
XBS5_LP64_OFF64_LIBSXBS5_LP64_OFF64_LINTFLAGS
XBS5_LPBIG_OFFBIGXBS5_LPBIG_OFFBIG_CFLAGS
XBS5_LPBIG_OFFBIG_LDFLAGSXBS5_LPBIG_OFFBIG_LIBS
XBS5_LPBIG_OFFBIG_LINTFLAGS_XOPEN_CRYPT
_XOPEN_ENH_I18N_XOPEN_IOV_MAX
_XOPEN_LEGACY_XOPEN_NAME_MAX
_XOPEN_PATH_MAX_XOPEN_SHM
_XOPEN_STREAMS_XOPEN_VERSION
_XOPEN_XCU_VERSION_XOPEN_XPG2
_XOPEN_XPG3_XOPEN_XPG4
.TE

.sp
.LP
The symbol \fBPATH\fR also is recognized, yielding the same value as the \fBconfstr()\fR name value \fBCS_PATH\fR.
.SH USAGE
.sp
.LP
See \fBlargefile\fR(5) for the description of the behavior of \fB/usr/bin/getconf\fR when encountering files greater than or equal to 2 Gbyte (2^31 bytes).
.SH EXAMPLES
.LP
\fBExample 1 \fRWriting the Value of a Variable
.sp
.LP
This example illustrates the value of \fB{NGROUPS_MAX}:\fR

.sp
.in +2
.nf
example% \fBgetconf NGROUPS_MAX\fR
.fi
.in -2
.sp

.LP
\fBExample 2 \fRWriting the Value of a Variable for a Specific Directory
.sp
.LP
This example illustrates the value of \fBNAME_MAX\fR for a specific directory:

.sp
.in +2
.nf
example% \fBgetconf NAME_MAX /usr\fR
.fi
.in -2
.sp

.LP
\fBExample 3 \fRDealing with Unspecified Results
.sp
.LP
This example shows how to deal more carefully with results that might be unspecified:

.sp
.in +2
.nf
if value=$(getconf PATH_MAX /usr); then
if [ "$value" = "undefined" ]; then
echo PATH_MAX in /usr is infinite.
else
echo PATH_MAX in /usr is $value.
fi
else
echo Error in getconf.
fi
.fi
.in -2

.sp
.LP
For example:

.sp
.in +2
.nf
sysconf(_SC_POSIX_C_BIND);
.fi
.in -2

.sp
.LP
and

.sp
.in +2
.nf
system("getconf POSIX2_C_BIND");
.fi
.in -2

.sp
.LP
in a C program could give different answers. The \fBsysconf\fR call supplies a value that corresponds to the conditions when the program was either compiled or executed, depending on the implementation. The \fBsystem\fR call to \fBgetconf\fR always supplies a value corresponding to conditions when the program is executed.

.SH ENVIRONMENT VARIABLES
.sp
.LP
See \fBenviron\fR(5) for descriptions of the following environment variables that affect the execution of \fBgetconf\fR: \fBLANG\fR, \fBLC_ALL\fR, \fBLC_CTYPE\fR, \fBLC_MESSAGES\fR, and \fBNLSPATH\fR.
.SH EXIT STATUS
.sp
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 6n
.rt  
The specified variable is valid and information about its current state was written successfully.
.RE

.sp
.ne 2
.mk
.na
\fB\fB>0\fR\fR
.ad
.RS 6n
.rt  
An error occurred.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Availabilitysystem/core-os
_
Interface StabilityCommitted
_
StandardSee \fBstandards\fR(5).
.TE

.SH SEE ALSO
.sp
.LP
\fBsh\fR(1), \fBpathconf\fR(2), \fBsysinfo\fR(2), \fBconfstr\fR(3C), \fBsysconf\fR(3C), \fBattributes\fR(5), \fBenviron\fR(5), \fBlargefile\fR(5), \fBstandards\fR(5)
