'\" te
.\" Copyright (c) 1992, 2011, Oracle and/or its affiliates. All rights reserved.
.TH hostname 1 "19 Jul 2011" "SunOS 5.11" "User Commands"
.SH NAME
hostname \- set or print name of current host system
.SH SYNOPSIS
.LP
.nf
\fB/usr/bin/hostname\fR [\fIname-of-host\fR]
.fi

.SH DESCRIPTION
.sp
.LP
The \fBhostname\fR command prints the name of the current host, as given before the \fBlogin\fR prompt. The super-user can set the hostname by giving an argument.
.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
\fBATTRIBUTE TYPE\fR\fBATTRIBUTE VALUE\fR
Availabilitysystem/core-os
.TE

.SH SEE ALSO
.sp
.LP
\fBuname\fR(1), \fBnodename\fR(4), \fBattributes\fR(5)
