'\" te
.\"  Copyright (c) 1988, 2011, Oracle and/or 
.TH tplot 1 "17 Aug 2011" "SunOS 5.11" "User Commands"
.SH NAME
tplot, t300, t300s, t4014, t450, tek, ver \- graphics filters for various plotters
.SH SYNOPSIS
.LP
.nf
\fB/usr/bin/tplot\fR [\fB-T\fR \fIterminal\fR]
.fi

.SH DESCRIPTION
.sp
.LP
\fBtplot\fR reads plotting instructions from the standard input and produces plotting instructions suitable for a particular \fIterminal\fR on the standard output.
.sp
.LP
If no \fIterminal\fR is specified, the environment variable \fBTERM\fR is used.  The default \fIterminal\fR is \fBtek\fR.
.SH FILES
.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/t300\fR\fR
.ad
.RS 18n
.rt  

.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/t300s\fR\fR
.ad
.RS 18n
.rt  

.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/t4014\fR\fR
.ad
.RS 18n
.rt  

.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/t450\fR\fR
.ad
.RS 18n
.rt  

.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/tek\fR\fR
.ad
.RS 18n
.rt  

.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/vplot\fR\fR
.ad
.RS 18n
.rt  

.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Availabilitysystem/core-os
.TE

.SH SEE ALSO
.sp
.LP
\fBvi\fR(1), \fBattributes\fR(5)
