#
# Copyright (c) 2005, 2010, Oracle and/or its affiliates. All rights reserved.
#
#

UTSTREE=$(UTSCLOSED)

include $(UTSBASE)/intel/Makefile.targ.shared
$(TONICBUILD)include $(UTSCLOSED)/../Makefile.tonic
