#
# Copyright (c) 2005, 2011, Oracle and/or its affiliates. All rights reserved.
#

#
#	This Makefile defines all file modules and build rules for the
# directory uts/intel and its children. These are the source files which
# are specific to the intel processor.
#
#	The following two-level ordering must be maintained in this file.
#	  Lines are sorted first in order of decreasing specificity based on
#	  the first directory component.  That is, sun4u rules come before
#	  sparc rules come before common rules.
#
#	  Lines whose initial directory components are equal are sorted
#	  alphabetically by the remaining components.

#
#	Section 1a: C object build rules
#

$(OBJS_DIR)/%.o:		$(UTSBASE)/intel/io/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/acpi_toshiba/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/atiatom/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/bmc/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/sbmc/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/ipmi/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

INTEL_NB5000_OT = $(UTSBASE)/intel/io/intel_nb5000
INTEL_NB5000_CT = $(UTSCLOSED)/intel/io/intel_nb5000

INTEL_NB5000_INC = -I $(INTEL_NB5000_CT) -I $(INTEL_NB5000_OT)

$(OBJS_DIR)/%.o:		$(INTEL_NB5000_CT)/%.c
	$(COMPILE.c) -o $@ $(INTEL_NB5000_INC) $<
	$(CTFCONVERT_O)

INTEL_NHM_OT = $(UTSBASE)/intel/io/intel_nhm
INTEL_NHM_CT = $(UTSCLOSED)/intel/io/intel_nhm

INTEL_NHM_INC = -I $(INTEL_NHM_CT) -I $(INTEL_NHM_OT)

$(OBJS_DIR)/%.o:		$(INTEL_NHM_CT)/%.c
	$(COMPILE.c) -o $@ $(INTEL_NHM_INC) $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/intel_nhmex/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/iprb/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/intel/io/memtest/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:  $(DRVDIR)/%.c $(ADPU_HEADERS) $(DRVDIR)/adpu320.h \
		  $(DRVDIR)/release.h
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:  $(CHIMDIR)/hwm/%.c $(ADPU_HEADERS)
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:  $(CHIMDIR)/rsm/%.c $(ADPU_HEADERS)
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:  $(CHIMDIR)/xlm/%.c $(ADPU_HEADERS)	
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

#
#	Section 1b: Lint `object' build rules
#

$(LINTS_DIR)/%.ln:		$(UTSBASE)/intel/io/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/acpi_toshiba/%.c
	@($(LHEAD) $(LINT.s) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/atiatom/%.c
	@($(LHEAD) $(LINT.s) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/bmc/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/sbmc/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/ipmi/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(INTEL_NB5000_CT)/%.c
	@($(LHEAD) $(LINT.c) $(INTEL_NB5000_INC) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(INTEL_NHM_CT)/%.c
	@($(LHEAD) $(LINT.c) $(INTEL_NHM_INC) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/intel_nhmex/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/iprb/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/intel/io/memtest/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))
