#
# Copyright (c) 2006, 2010, Oracle and/or its affiliates. All rights reserved.
#

.KEEP_STATE:
.PARALLEL: $(SUBDIRS)

include $(SRC)/cmd/Makefile.cmd
$(TONICBUILD)include $(CLOSED)/Makefile.tonic

all		:= TARGET = all
clean.lint	:= TARGET = clean.lint
clean		:= TARGET = clean
clobber		:= TARGET = clobber
install		:= TARGET = install
lint		:= TARGET = lint

all clean.lint clean clobber install lint: $(SUBDIRS)

$(SUBDIRS): FRC
	@cd $@; pwd; $(MAKE) $(TARGET)

FRC:
