#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"

sparc_SUBDIRS = sparc
i386_SUBDIRS = x86
SUBDIRS=$($(MACH)_SUBDIRS)

include ./Makefile.subdirs
