#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
#	This Makefile defines the build rules for the directory
#	uts/sun4u/opl and its children.
#
# uts/sun4u/opl/Makefile.rules
#

#
# C object build rules

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4u/opl/io/scfd/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

#
#	Section 1b: Lint object build rules
#

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4u/opl/io/scfd/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

.KEEP_STATE:
