#!/usr/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2004, 2011, Oracle and/or its affiliates. All rights reserved.
#

#
# Start/Stop client LDAP service
#

. /lib/svc/share/smf_include.sh

case "$1" in
'start')
	# Test and import if upgrade
	/usr/sbin/nscfg import -q $SMF_FMRI
	err=$?
	if [ $err -eq 1 ] ; then
		echo "WARNING: $SMF_FMRI configuration import error." >& 2
		exit $SMF_EXIT_ERR_CONFIG
	elif [ $err -eq 3 ] ; then
		echo "WARNING: $SMF_FMRI no configuration." >& 2
	fi
	/usr/sbin/nscfg export $SMF_FMRI
	err=$?
	if [ $err -eq 1 ] ; then
		echo "WARNING: $SMF_FMRI configuration export error." >& 2
		exit $SMF_EXIT_ERR_CONFIG
	fi
	if [ ! -r /var/ldap/ldap_client_file ]; then
		echo "WARNING: /var/ldap/ldap_client_file is missing or not readable" >& 2
		exit $SMF_EXIT_ERR_CONFIG
	fi

	exec /usr/lib/ldap/ldap_cachemgr
	;;

'refresh')
	/usr/sbin/nscfg export $SMF_FMRI
	if [ $? -eq 2 ] ; then
		exit $SMF_EXIT_OK
	fi
	/usr/bin/pkill -HUP ldap_cachemgr
	;;

'stop')
	exec /usr/lib/ldap/ldap_cachemgr -K
	;;

'unconfigure')
	# Permanently shutdown service
	svcadm disable $SMF_FMRI 
	# Unroll any admin customization
	svccfg -s svc:/network/ldap/client delcust
	if [ $? -ne 0 ]; then
		echo "Failed to unroll administrative customizations for $SMF_FMRI"
		exit $SMF_EXIT_ERR_FATAL
	fi
	rm -rf /var/ldap/*
	;;

*)
	echo "Usage: $0 { start | refresh | stop | unconfigure }"
	exit 1
	;;
esac
