#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
#

#
# Startup script for the devchassisd(1M) daemon.
#

. /lib/svc/share/smf_include.sh

# The devchassis service is only supported in the global zone.
smf_assert_globalzone

# Check for a devchassisd process and exit if the daemon is already running.
if /usr/bin/pgrep -x -u 0 devchassisd >/dev/null 2>&1; then
	echo "$0: devchassisd is already running"
	exit 1
fi

# Start the daemon.
exec /usr/lib/devchassis/devchassisd
