'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1992, Sun Microsystems, Inc. All Rights Reserved
.TH ckgid 1 "1992 年 9 月 14 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
ckgid, errgid, helpgid, valgid \- グループ ID の入力要求とその検証
.SH 形式
.LP
.nf
\fBckgid\fR [\fB-Q\fR] [\fB-W\fR \fIwidth\fR] [\fB-m\fR] [\fB-d\fR \fIdefault\fR] [\fB-h\fR \fIhelp\fR] 
     [\fB-e\fR \fIerror\fR] [\fB-p\fR \fIprompt\fR] [\fB-k\fR \fIpid\fR [\fB-s\fR \fIsignal\fR]]
.fi

.LP
.nf
\fB/usr/sadm/bin/errgid\fR [\fB-W\fR \fIwidth\fR] [\fB-e\fR \fIerror\fR]
.fi

.LP
.nf
\fB/usr/sadm/bin/helpgid\fR [\fB-W\fR \fIwidth\fR] [\fB-m\fR] [\fB-h\fR \fIhelp\fR]
.fi

.LP
.nf
\fB/usr/sadm/bin/valgid\fR \fIinput\fR
.fi

.SH 機能説明
.sp
.LP
\fBckgid\fR は、ユーザーに入力を要求するプロンプトを出力し、ユーザーの応答を検証します。このユーティリティでは、ユーザーに既存のグループ ID の入力を促すプロンプトメッセージ、ヘルプメッセージとエラーメッセージ、およびデフォルト値 (ユーザーがキャリッジリターンで応答した場合に返される値) をオプションにより定義できます。
.sp
.LP
メッセージの長さはすべて最大 70 文字に制限され、自動的に書式化されます。定義で使用されるスペース (復帰改行を含む) はすべて削除されます。\fB-W\fR オプションは、自動書式化を取り消します。メッセージ定義の最初または最後にチルド文字がある場合は、そこにデフォルトテキストが挿入されて、指定したテキストとデフォルトテキストの両方を表示することができます。
.sp
.LP
プロンプトメッセージ、ヘルプメッセージ、またはエラーメッセージが定義されていない場合は、デフォルトメッセージ (\fB「注意事項」\fRの項を参照) が表示されます。
.sp
.LP
\fBckgid\fR コマンドには、3 つのビジュアルツールモジュールがリンクされています。これらのモジュールは、\fBerrgid\fR (エラーメッセージを書式化して表示する)、\fBhelpgid\fR (ヘルプメッセージを書式化して表示する)、および \fBvalgid\fR (応答を検証する) です。これらのモジュールは、\fBFML\fR オブジェクトと組み合わせて使用する必要があります。この場合、\fBFML\fR オブジェクトはプロンプトを定義します。
.SH オプション
.sp
.LP
次のオプションがサポートされています。
.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fI default\fR\fR
.ad
.RS 14n
.rt  
\fIdefault\fR をデフォルト値として定義します。デフォルト値は検証されないため、どのような基準も満たす必要はありません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-e\fR\fI error\fR\fR
.ad
.RS 14n
.rt  
\fIerror\fR をエラーメッセージとして定義します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-h\fR\fI help\fR\fR
.ad
.RS 14n
.rt  
\fIhelp\fR をヘルプメッセージとして定義します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-k\fR\fI pid\fR\fR
.ad
.RS 14n
.rt  
ユーザーが中断を選択した場合、プロセス \fBID\fR \fIpid\fR のプロセスにシグナルを送信するようにします。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-m\fR\fR
.ad
.RS 14n
.rt  
ユーザーがヘルプを要求した場合、あるいはユーザーの入力が不正な場合は、グループ名の一覧を表示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-p\fR\fI prompt\fR\fR
.ad
.RS 14n
.rt  
\fIprompt\fR をプロンプトメッセージとして定義します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-Q\fR\fR
.ad
.RS 14n
.rt  
有効な応答として終了 (quit) を使用できないようにします。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fI signal\fR\fR
.ad
.RS 14n
.rt  
終了が選択された場合、\fB-k\fR オプションで定義されたプロセス \fBID\fR \fIpid\fR のプロセスに、シグナル \fIsignal\fR を送信するようにします。シグナルを指定しないと、\fBSIGTERM\fR を送信します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-W\fR\fI width\fR\fR
.ad
.RS 14n
.rt  
プロンプトメッセージ、ヘルプメッセージ、およびエラーメッセージを、\fIwidth\fR の行長に書式化します。
.RE

.SH オペランド
.sp
.LP
次のオペランドがサポートされています。
.sp
.ne 2
.mk
.na
\fB\fIinput\fR\fR
.ad
.RS 9n
.rt  
\fB/etc/group\fR と照合される入力
.RE

.SH 終了ステータス
.sp
.LP
次の終了値が返されます。
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
正常終了。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
入力で \fBEOF\fR が検出された、\fB-W\fR オプションで負の行長が指定された、または使用法に誤りがあった。
.RE

.sp
.ne 2
.mk
.na
\fB\fB3\fR\fR
.ad
.RS 5n
.rt  
ユーザー終了 (quit)。
.RE

.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBattributes\fR(5)
.SH 注意事項
.sp
.LP
\fBckgid\fR のデフォルトのプロンプトは、次のとおりです。
.sp
.in +2
.nf
Enter the name of an existing group [?,q]:
.fi
.in -2
.sp

.sp
.LP
デフォルトのエラーメッセージは、次のとおりです。
.sp
.in +2
.nf
ERROR: Please enter one of the following group names: [\fIList\fR]
.fi
.in -2
.sp

.sp
.LP
\fBckgid\fR の \fB-m\fR オプションを使用すると、有効なグループのリストがここに表示されます。
.sp
.LP
デフォルトのヘルプメッセージは、次のとおりです。
.sp
.in +2
.nf
ERROR: Please enter one of the following group names: [\fIList\fR]
.fi
.in -2
.sp

.sp
.LP
\fBckgid\fR の \fB-m\fR オプションを使用すると、有効なグループのリストがここに表示されます。
.sp
.LP
終了オプションを選択した場合 (かつ使用できる場合) は、リターンコード \fB3\fR と共に \fBq\fR が返されます。\fBvalgid\fR モジュールは、出力を生成しません。正常終了した場合は \fB0\fR、失敗した場合には 0 以外の値を返します。
