'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1996, Sun Microsystems, Inc. All Rights Reserved
.TH factor 1 "1996 年 1 月 31 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
factor \- 素因数の分解
.SH 形式
.LP
.nf
\fBfactor\fR [\fIinteger\fR]
.fi

.SH 機能説明
.sp
.LP
\fBfactor\fR は、10^14 以下の正の整数の、すべての素因数を標準出力に書き込みます。素因数は適切な回数だけ書き込まれます。
.sp
.LP
\fBfactor\fR を引数なしで実行した場合、factor は整数が入力されるのを待ちます。\fI\fR整数が入力されると、factor はその整数を素因数に分解し、適切な回数だけ出力して、再び整数が入力されるのを待ちます。0 または数値以外の文字を入力すると、\fBfactor\fR は終了します。
.sp
.LP
引数 (整数) を指定して \fBfactor\fR を実行すると、factor はその整数を出力し、素因数に分解して、すべての素因数を前述のと同様に出力し、終了します。\fI\fR\fI\fR引数が 0 または数値以外の文字の場合、\fBfactor\fR は 0 を出力して終了します。
.sp
.LP
整数を素因数分解する最大時間は sqrt(n) (\fIn\fR は入力する整数) に比例します。\fIn\fR が素数または素数の二乗である場合、\fBfactor\fR は、素因数の計算にこの最大時間を必要とします。
.SH オペランド
.sp
.ne 2
.mk
.na
\fB\fIinteger\fR\fR
.ad
.RS 11n
.rt  
10^14 以下の正の整数
.RE

.SH 終了ステータス
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
正常終了。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
エラーが発生しました。
.RE

.SH 診断
.sp
.LP
範囲外の数値や意味のない文字の入力に対しては、\fBfactor\fR は「\fBOuch!\fR」というエラーメッセージを出力します。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/extended-system-utilities
.TE

.SH 関連項目
.sp
.LP
\fBattributes\fR(5)
