'\" te
.\" Copyright (c) 2008, Sun Microsystems Inc. All Rights Reserved.
.TH getlabel 1 "2008 年 7 月 11 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
getlabel \- ファイルのラベルの表示
.SH 形式
.LP
.nf
\fB/usr/bin/getlabel\fR [\fB-sS\fR] \fI filename\fR...
.fi

.SH 機能説明
.sp
.LP
\fBgetlabel\fR は、各 \fIfilename\fR に関連付けられているラベルを表示します。オプションを指定しない場合、 ラベルはデフォルト形式で表示されます。
.SH オプション
.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fR
.ad
.RS 6n
.rt  
\fIfilename\fR に関連付けられているラベルを短形式で表示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-S\fR\fR
.ad
.RS 6n
.rt  
\fIfilename\fR に関連付けられているラベルを長形式で表示します。
.RE

.SH 終了ステータス
.sp
.LP
\fBgetlabel\fR は、終了時に次のいずれかの値を返します。
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
正常終了。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
使用方法の誤りのためエラー終了しました。
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR\fR
.ad
.RS 5n
.rt  
ラベルを変換できませんでした。
.RE

.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ 属性値
_
使用条件system/trusted
_
インタフェースの安定性 下記を参照。
.TE

.sp
.LP
コマンド行は「確実」です。出力は非インタフェースです。
.SH 関連項目
.sp
.LP
\fBsetlabel\fR(1), \fBm_label\fR(3TSOL), \fBlabel_encodings\fR(4), \fBattributes\fR(5)
.SH 注意事項
.sp
.LP
このマニュアルページに記載されている機能を利用できるのは、システムが Trusted Extensions を使用して構成されている場合だけです。
