'\" te
.\" Copyright (c) 2007, Sun Microsystems, Inc. All Rights Reserved.
.TH getzonepath 1 "2007 年 7 月 20 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
getzonepath \- 指定したラベルに対応するゾーンのルートパスの表示
.SH 形式
.LP
.nf
\fB/usr/bin/getzonepath\fR {\fIsensitivity-label\fR}
.fi

.SH 機能説明
.sp
.LP
\fBgetzonepath\fR は、指定した機密ラベルに対応する、実行中のラベル付きゾーンのルートパス名を表示します。返されるパス名は、呼び出し元のルートパス名に対する相対パスで、指定された機密ラベルが付けられています。
.sp
.LP
呼び出し元が大域ゾーン内に存在する場合、呼び出し側のプロセスが \fBfile_dac_search\fR 特権を保持しない限り、返されるパスをたどることはできません。
.sp
.LP
呼び出し側がラベル付きのゾーン内に存在する場合、呼び出し側のラベルが指定したラベルよりも優位でなければなりません。返されたパス名内部のファイルへのアクセスは、読み取り専用操作に限定されています。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/trusted
_
安定性確実
.TE

.SH 診断
.sp
.LP
\fBgetzonepath\fR は、終了時に次のいずれかの値を返します。
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
成功
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
使用上のエラー
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR\fR
.ad
.RS 5n
.rt  
異常終了。エラーメッセージとして \fBgetzonerootbylabel\fR(3TSOL) のシステムエラー番号が返される
.RE

.SH 関連項目
.sp
.LP
\fBgetzonerootbylabel\fR(3TSOL), \fBattributes\fR(5)
.sp
.LP
\fI「Acquiring a Sensitivity Label」\fR in \fI『Oracle Solaris Trusted Extensions Developer\&'s Guide』\fR
.SH 注意事項
.sp
.LP
このマニュアルページに記載されている機能を利用できるのは、システムが Trusted Extensions を使用して構成されている場合だけです。
