'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1992, Sun Microsystems, Inc. All Rights Reserved
.TH groups 1 "1992 年 9 月 14 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
groups \- ユーザーのグループメンバーシップの出力
.SH 形式
.LP
.nf
\fBgroups\fR [\fIuser\fR]...
.fi

.SH 機能説明
.sp
.LP
\fBgroups\fR コマンドは、このコマンドを実行したユーザーの、または指定したユーザーの所属グループを標準出力に書き込みます。各ユーザーは \fB/etc/passwd\fR 内に指定されているグループに属し、さらに \fB/etc/group\fR 内に指定されているほかのグループにも属している可能性があります。\fB/etc/passwd\fR では、グループの \fBID\fR (\fBgid\fR) は数値で指定されています。\fBgroups\fR コマンドは \fBgid\fR をグループ名に変換して出力します。
.SH 使用例
.sp
.LP
出力の形式は次のとおりです。
.sp
.in +2
.nf
example% groups tester01 tester02
tester01 : staff
tester02 : staff
example%
.fi
.in -2
.sp

.SH ファイル
.sp
.ne 2
.mk
.na
\fB\fB/etc/passwd\fR\fR
.ad
.RS 15n
.rt  

.RE

.sp
.ne 2
.mk
.na
\fB\fB/etc/group\fR\fR
.ad
.RS 15n
.rt  

.RE

.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBgroup\fR(4), \fBpasswd\fR(4), \fBattributes\fR(5)
