'\" te
.\" Copyright (c) 1992, 2011, Oracle and/or its affiliates. All rights reserved.
.TH hostname 1 "2011 年 7 月 19 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
hostname \- 現在のホストシステムの名前の設定または出力
.SH 形式
.LP
.nf
\fB/usr/bin/hostname\fR [\fIname-of-host\fR]
.fi

.SH 機能説明
.sp
.LP
\fBhostname\fR コマンドは、\fBlogin\fR プロンプトの前に表示されている現在のホストの名前を出力します。スーパーユーザーは、引数を指定してホスト名を設定できます。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
\fB属性タイプ\fR\fB属性値\fR
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBuname\fR(1), \fBnodename\fR(4), \fBattributes\fR(5)
