'\" te
.\" Copyright (c) 2009 Sun Microsystems, Inc. - All Rights Reserved.
.TH hostid 1 "2009 年 2 月 4 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
hostid \- 現在のホストの数値識別子の出力
.SH 形式
.LP
.nf
\fB/usr/bin/hostid\fR 
.fi

.SH 機能説明
.sp
.LP
\fBhostid\fR コマンドは、現在のホストの識別子を 16 進数で出力します。ホスト識別子をエミュレートする非大域ゾーン内で実行した場合、エミュレートされたホスト識別子が出力されます。通常、\fBhostid\fR を別のマシンで実行した場合、この数値は異なります。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
\fB属性タイプ\fR\fB属性値\fR
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBsysinfo\fR(2), \fBgethostid\fR(3C), \fBattributes\fR(5), \fBzones\fR(5)
