'\" te
.\"  Copyright (c) 2008, Sun Microsystems, Inc. All Rights Reserved
.TH isalist 1 "2008 年 3 月 20 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
isalist \- このプラットフォームで実行可能なネイティブ命令セットを表示する
.SH 形式
.LP
.nf
\fBisalist\fR 
.fi

.SH 機能説明
.sp
.LP
\fBisalist\fR は、\fBsysinfo\fR(2) の \fBSI_ISALIST\fR コマンドが返すように、このプラットフォームで実行可能なネイティブ命令セットの名前を標準出力に書き込みます。
.sp
.LP
名前はスペースで区切られ、最適なパフォーマンスの順に表示されます。つまり、先に表示された命令セットには、あとに表示された命令セット以上の命令が含まれている場合があります。このため、このマシンではほとんどの場合、先に表示された命令セット用にコンパイルされたプログラムは、あとに表示された命令セット用にコンパイルされた同じプログラムよりも高速に動作します。
.sp
.LP
このマシンではほとんどの場合、このリストに表示されない命令セット用にコンパイルされたプログラムは、パフォーマンスの低下を引き起こすか、まったく動作しません。
.sp
.LP
システムが認識する命令セットの名前は、\fBisalist\fR(5) のリストに表示されます。これらの名前は、C 言語処理系の定義済みの名前やコンパイラオプションに一致する場合も一致しない場合もあります。
.sp
.LP
このコマンドは廃止または、互換性がなくなる可能性があり、Solaris の将来のバージョンでは削除されることがあります。命令セット拡張機能のより良い処理方法については、\fBisainfo\fR(1)  を参照してください。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
\fB属性タイプ\fR\fB属性値\fR
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBisainfo\fR(1), \fBoptisa\fR(1), \fBuname\fR(1), \fBsysinfo\fR(2), \fBattributes\fR(5), \fBisalist\fR(5)
