'\" te
.\"  Copyright 1989 AT&T
.\" Copyright (c) 1990, 2010, Oracle and/or its affiliates. All rights reserved.
.TH machid 1 "2010 年 12 月 7 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
machid, sun, i386, i486, sparc \- プロセッサタイプの真理値の取得
.SH 形式
.LP
.nf
\fBsun\fR 
.fi

.LP
.nf
\fBi386\fR 
.fi

.LP
.nf
\fBsparc\fR 
.fi

.SH 機能説明
.sp
.LP
次のコマンドは、コマンド名が示す命令セットを使用する場合、真の値 (終了コードは 0) を返します。
.sp
.ne 2
.mk
.na
\fB\fBsun\fR\fR
.ad
.RS 9n
.rt  
Sun システムであれば真。
.RE

.sp
.ne 2
.mk
.na
\fB\fBi386\fR\fR
.ad
.RS 9n
.rt  
iAPX386 プロセッサを使用するコンピュータであれば真。
.RE

.sp
.ne 2
.mk
.na
\fB\fBsparc\fR\fR
.ad
.RS 9n
.rt  
SPARC ファミリのプロセッサを使用するコンピュータであれば真。
.RE

.sp
.LP
該当しないコマンドは偽 (0 以外) の値を返します。これらのコマンドは、可搬性を高めるために、メイクファイル (\fBmake\fR(1S) を参照) およびシェルスクリプト (\fBsh\fR(1) を参照) 内でよく使用されます。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBmake\fR(1S), \fBsh\fR(1), \fBtest\fR(1), \fBtrue\fR(1), \fBuname\fR(1), \fBattributes\fR(5)
.SH 注意事項
.sp
.LP
\fBmachid\fR ファミリのコマンドは廃止されました。代わりに \fBuname\fR \fB-p\fR および \fBuname\fR \fB-m\fR を使用してください。
