'\" te
.\"  Copyright (c) 1996 Sun Microsystems, Inc. - All Rights Reserved.
.TH mach 1 "1996 年 1 月 18 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
mach \- 現在のホストのプロセッサタイプの表示
.SH 形式
.LP
.nf
\fBmach\fR 
.fi

.SH 機能説明
.sp
.LP
\fBmach\fR コマンドは、現在のホストのプロセッサタイプを表示します。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
\fB属性タイプ\fR\fB属性値\fR
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBarch\fR(1), \fBuname\fR(1), \fBattributes\fR(5)
.SH 注意事項
.sp
.LP
\fBmach\fR および \fBuname\fR \fB-p\fR は同等の値を返します。そのため独立ソフトウェアベンダー (ISV) やその他のベンダーでプロセッサタイプを確認する必要がある場合、\fBmach\fR コマンドではなく \fBuname\fR を \fB-p\fR オプションとともに使用することをお勧めします。\fBmach\fR コマンドは以前のリリースとの互換性確保のために提供されており、通常は使用しないようにしてください。
