'\" te
.\" Copyright (c) 2008, Sun Microsystems, Inc. All Rights Reserved.
.\" Copyright 1989 AT&T
.TH makekey 1 "2008 年 3 月 3 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
makekey \- 暗号化鍵の生成
.SH 形式
.LP
.nf
\fB/usr/lib/makekey\fR
.fi

.SH 機能説明
.sp
.LP
\fBmakekey\fR は、鍵空間の検索に必要な時間を増大させることで、その鍵に依存する暗号化方式の有効性を高めます。8 バイトが鍵 (入力の最初の 8 バイト) として読み取られ、次に 2 バイトがソルト (入力の最後の 2 バイト) として読み取られます。\fI\fR\fI\fR入力に応じて出力が変わるため、出力の計算が難しくなります (数分の 1 秒を要します)。
.sp
.LP
入力の最初の 8 バイト (入力鍵) は、任意の \fBASCII\fR 文字列にできます。\fI\fR最後の 2 バイト (ソルト) は、数字、\fB\&.\fR、\fB/\fR、大文字、および小文字を組み合わせて選択することをお勧めします。\fI\fRソルト文字は、出力の最初の 2 文字として繰り返されます。出力の残りの 11 文字は、ソルトと同じセットから選択され、出力鍵を構成します。\fI\fR\fI\fR
.sp
.LP
変換の実行により、基本的に次のような動作が行われます。ソルトが使用され、4,096 個の暗号機のいずれかが選択されます。これらの暗号機はすべて米規格基準局の \fBDES\fR アルゴリズムに基づいていますが、その解読方法は 4,096 とおり存在します。\fI\fR入力鍵が鍵として使用され、定数文字列を暗号機に入力する処理が何度も繰り返されます。\fI\fR\fI\fR算出された 64 ビットが、結果として得られる出力鍵の 66 ビットに分配されます。\fI\fR\fI\fR
.sp
.LP
\fBmakekey\fR は、暗号化を実行するプログラムの用に提供されています。通常、その入力と出力はパイプです。
.SH 関連項目
.sp
.LP
\fBed\fR(1), \fBvi\fR(1), \fBpasswd\fR(4)
.SH 注意事項
.sp
.LP
\fBmakekey\fR で生成される結果は、入力が端末で実行されたか、ファイルからリダイレクトされたかによって異なります。
