'\" te
.\"  Copyright (c) 1997 Sun Microsystems, Inc. All Rights Reserved.
.TH optisa 1 "1997 年 7 月 25 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
optisa \- さまざまな命令セットから最適に使用できるものを決定
.SH 形式
.LP
.nf
\fBoptisa\fR \fIinstruction_set\fR...
.fi

.SH 機能説明
.sp
.LP
\fBoptisa\fR は、コマンドで指定した \fIinstruction_set\fR のうち、このマシンで最適に機能するものを表示します。この場合、「最適」は \fBisalist\fR(1) で返される命令セット名の順序に従って定義されます。\fIinstruction_set\fR に使用可能な値は、\fBisalist\fR(5) に表示されています。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/core-os
.TE

.SH 終了ステータス
.sp
.LP
次の終了値が返されます。
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
指定した \fIinstruction_set\fR 値のいずれかがこのコマンドによって表示されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
出力がありません。つまり、このマシンは \fBoptisa\fR コマンドで指定したどの \fIinstruction_set\fR も使用できません。
.RE

.SH 関連項目
.sp
.LP
\fBisalist\fR(1), \fBuname\fR(1), \fBattributes\fR(5), \fBisalist\fR(5)
.SH 注意事項
.sp
.LP
特定のマシン上で、特定のプログラムの複数のバイナリバージョンのうちどれを使用するべきかを決定する場合は、\fBuname\fR \fB-p\fR や \fBuname\fR \fB-m\fR (\fBuname\fR(1) を参照) よりも、\fBoptisa\fR を使用することをお勧めします。
