'\" te
.\" Copyright (c) 2007, Sun Microsystems, Inc. All Rights Reserved.
.TH plabel 1 "2007 年 7 月 20 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
plabel \- プロセスのラベルの取得
.SH 形式
.LP
.nf
\fB/usr/bin/plabel\fR [\fB-sS\fR] [\fI pid\fR...]
.fi

.SH 機能説明
.sp
.LP
\fBplabel\fR は、プロセスのラベルを取得するプロセスツールコマンドです。\fIpid\fR を指定しない場合は、\fBplabel\fR コマンドのラベルが表示されます。オプションを指定しない場合、 ラベルはデフォルト形式で表示されます。
.SH オプション
.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fR
.ad
.RS 6n
.rt  
\fIpid\fR に関連付けられているラベルを短形式で表示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-S\fR\fR
.ad
.RS 6n
.rt  
\fIpid\fR に関連付けられているラベル長形式で表示します。
.RE

.SH 終了ステータス
.sp
.LP
\fBplabel\fR は、終了時に次のいずれかの値を返します。
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
正常終了。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
使用方法の誤りのためエラー終了しました。
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR\fR
.ad
.RS 5n
.rt  
ラベルを変換できなかった。
.RE

.sp
.ne 2
.mk
.na
\fB\fB3\fR\fR
.ad
.RS 5n
.rt  
メモリーを割り当てられなかった。
.RE

.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/trusted
_
インタフェースの安定性下記を参照。
.TE

.sp
.LP
\fBplabel\fR ユーティリティーは「確実」です。出力は非インタフェースです。
.SH 関連項目
.sp
.LP
\fBproc\fR(1), \fBgetplabel\fR(3TSOL), \fBattributes\fR(5)
.SH 注意事項
.sp
.LP
このマニュアルページで説明されている機能を使用できるのは、システムが Trusted Extensions で構成されている場合だけです。
