'\" te
.\" Copyright (c) 2000 Sun Microsystems, Inc., All Rights Reserved.
.TH setpgrp 1 "2000 年 1 月 5 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
setpgrp \- プロセスグループ ID の設定
.SH 形式
.LP
.nf
\fBsetpgrp\fR \fIcommand\fR [\fIarg\fR]...
.fi

.SH 機能説明
.sp
.LP
現在のプロセスがまだセッションリーダーではない場合、\fBsetpgrp\fR ユーティリティーはプロセスグループ \fBID\fR とセッション \fBID\fR に現在のプロセス \fBID\fR を設定し、\fIcommand\fR とその引数 (存在する場合) の \fBexec()\fR を行います。
.SH オペランド
.sp
.LP
次のオペランドがサポートされています。
.sp
.ne 2
.mk
.na
\fB\fIcommand\fR\fR
.ad
.RS 11n
.rt  
呼び出すコマンドの名前。
.RE

.sp
.ne 2
.mk
.na
\fB\fIarg\fR \fR
.ad
.RS 11n
.rt  
\fIcommand\fR のオプションまたは引数。
.RE

.SH 終了ステータス
.sp
.LP
次の終了値が返されます。
.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
\fBsetpgrp\fR ユーティリティーの実行中、または \fIcommand\fR の \fBexec()\fR の際にエラーが発生しました。
.RE

.sp
.LP
それ以外の場合、終了ステータスは \fIcommand\fR の終了ステータスとなります。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBexec\fR(2), \fBsetpgrp\fR(2), \fBattributes\fR(5)
