'\" te
.\"  Copyright (c) 1997, 2011, Oracle and/or its affiliates. All rights reserved.
.TH sotruss 1 "2011 年 6 月 8 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
sotruss \- 共有ライブラリプロシージャ呼び出しの追跡
.SH 形式
.LP
.nf
\fB/usr/bin/sotruss\fR [\fB-f\fR] [\fB-F\fR \fIbindfromlist\fR] [\fB-T\fR \fIbindtolist\fR] 
     [\fB-o\fR \fIoutputfile\fR] executable [executable arguments...]
.fi

.SH 機能説明
.sp
.LP
\fBsotruss\fR は、指定されたコマンドを実行し、実行したライブラリ呼び出しのトレースを生成します。トレース出力の各行では、各プロシージャ呼び出しが実行されたときに動的オブジェクト間で発生する結合が報告されます。\fBsotruss\fR は、\fIプロシージャリンケージテーブル\fRを介して動的オブジェクト間で発生するすべてのプロシージャ呼び出しを追跡します。そのため、その\fIプロシージャ\fR\fIリンケージ\fR\fIテーブル\fRを介して結合されているプロシージャ呼び出しだけが追跡されます。『\fI『Linker and Libraries Guide』\fR』を参照してください。
.SH オプション
.sp
.ne 2
.mk
.na
\fB\fB-F\fR\fI bindfromlist\fR\fR
.ad
.RS 19n
.rt  
追跡するライブラリのコロンで区切られたリスト。これらのライブラリからの呼び出しだけが追跡されます。デフォルトでは、メインの実行可能オブジェクトからの呼び出しだけが追跡されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-T\fR\fI bindtolist\fR\fR
.ad
.RS 19n
.rt  
追跡するライブラリのコロンで区切られたリスト。これらのライブラリへの呼び出しだけが追跡されます。デフォルトでは、すべての呼び出しが追跡されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-o\fR \fIoutputfile\fR \fR
.ad
.RS 19n
.rt  
\fBsotruss\fR の出力を \fIoutputfile\fR に送ります。このオプションを \fB-f\fR オプションと組み合わせると、実行しているプログラムの \fIpid\fR がファイル名の後ろに付けられます。デフォルトでは、\fBsotruss\fR の出力は \fBstderr\fR に書き込まれます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR\fR
.ad
.RS 19n
.rt  
\fBfork()\fR によって作成されたすべての子プロセスを追跡し、各子プロセスの \fBtruss\fR 出力を書き込みます。このオプションを指定すると、各 \fBtruss\fR の出力行に \fIpid\fR が出力されます。
.RE

.SH 使用例
.LP
\fB例 1 \fR\fBsotruss\fR の例。
.sp
.LP
次の簡単な例では、単純な \fBls\fR コマンドの追跡を示します。

.sp
.in +2
.nf
% sotruss ls | more
ls       ->     libc.so.1:*atexit(0xef7d7d1c, 0x23c00, 0x0)
ls       ->     libc.so.1:*atexit(0x1392c, 0xef7d7d1c, 0xef621bb0)
ls       ->     libc.so.1:*setlocale(0x6, 0x1396c, 0xef621ba8)
ls       ->     libc.so.1:*textdomain(0x13970, 0x1396c, 0xef621ba8)
ls       ->     libc.so.1:*time(0x0, 0xef61f6fc, 0xef621ba8)
ls       ->     libc.so.1:*isatty(0x1, 0xef61f6fc, 0x0)
ls       ->     libc.so.1:*getopt(0x1, 0xeffff8fc, 0x13980)
ls       ->     libc.so.1:*malloc(0x100, 0x0, 0x0)
ls       ->     libc.so.1:*malloc(0x9000, 0x0, 0x0)
ls       ->     libc.so.1:*lstat64(0x23ee8, 0xeffff7a0, 0x0)
\&...
ls       ->     libc.so.1:*printf(0x13a64, 0x26208, 0x23ef0)
ls       ->     libc.so.1:*printf(0x13a64, 0x26448, 0x23ef0)
ls       ->     libc.so.1:*exit(0x0, 0x24220, 0x2421c)
.fi
.in -2
.sp

.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件developer/base-developer-utilities
.TE

.SH 関連項目
.sp
.LP
\fBld.so.1\fR(1), \fBtruss\fR(1), \fBwhocalls\fR(1), \fBfork\fR(2), \fBattributes\fR(5)
.sp
.LP
\fI『Linker and Libraries Guide』\fR
