'\" te
.\"  Copyright (c) 1995, 2011, Oracle and/or its affiliates. All rights reserved.
.TH symorder 1 "2011 年 6 月 8 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
symorder \- シンボルリストの並べ替え
.SH 形式
.LP
.nf
\fBsymorder\fR [\fB-s\fR] \fIobjectfile\fR \fIsymbolfile\fR
.fi

.SH 機能説明
.sp
.LP
\fBsymorder\fR は、SunOS 4.\fIx\fR で特に \fBvmunix\fR からシンボルを取得するオーバーヘッドを削減するために使用されていました。カーネルシンボルのエントリは \fB/dev/ksyms\fR から動的に取得されるため、これが適用されなくなりました。
.sp
.LP
このスクリプトは、さまざまなオペレーティングシステム間で移植可能なスクリプトを保守する必要があるソフトウェア開発者に役立つように提供されています。
.SH 終了ステータス
.sp
.LP
\fBsymorder\fR の終了ステータスは \fB0\fR です。
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
\fB属性タイプ\fR\fB属性値\fR
使用条件developer/base-developer-utilities
.TE

.SH 関連項目
.sp
.LP
\fBnlist\fR(3ELF), \fBattributes\fR(5), \fBksyms\fR(7D).
