'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1994 Sun Microsystems, Inc. - All Rights Reserved.
.TH times 1 "1994 年 4 月 15 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
times \- 現在のシェルの時間使用を報告するためのシェル組み込み関数 
.SH 形式
.SS "sh"
.LP
.nf
\fBtimes\fR 
.fi

.SS "ksh"
.LP
.nf
\fBtimes\fR 
.fi

.SH 機能説明
.SS "sh"
.sp
.LP
シェルから実行されたプロセスの、 ユーザー時間およびシステム時間の累計値を表示します。
.SS "ksh"
.sp
.LP
シェルおよびシェルから実行されたプロセスの、ユーザー時間およびシステム時間の累計値を表示します。
.sp
.LP
1 つまたは 2 つのアスタリスク (*) が先頭に付加されている \fBksh\fR(1) コマンドは、以下のような特殊な処理を受けます。
.RS +4
.TP
1.
コマンドが完了しても、コマンドの直前の変数代入リストは依然として有効です。
.RE
.RS +4
.TP
2.
入出力のリダイレクトは変数代入後に行われます。
.RE
.RS +4
.TP
3.
エラーが発生すると、それを含むスクリプトは中止されます。
.RE
.RS +4
.TP
4.
変数代入形式で、** から始まるコマンドに続くワードは、変数代入と同一の規則で展開されます。つまり、チルド置換は \fB=\fR 符号の後に実行され、ワード分割とファイル名生成は実行されません。
.RE
.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/core-os
.TE

.SH 関連項目
.sp
.LP
\fBksh\fR(1), \fBsh\fR(1), \fBtime\fR(1), \fBattributes\fR(5)
