'\" te
.\" Copyright (c) 1997, 2011, Oracle and/or its affiliates. All rights reserved.
.TH volcheck 1 "2011 年 8 月 15 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
volcheck \- ドライブ内にメディアがあるかどうかの確認
.SH 形式
.LP
.nf
\fBvolcheck\fR [\fB-v\fR] [\fB-i\fR \fIsecs\fR] [\fB-t\fR \fIsecs\fR] \fIpathname\fR
.fi

.SH 機能説明
.sp
.LP
\fBvolcheck\fR ユーティリティーは、各 \fBdev/\fR\fIpathname\fR を順に調べ、ドライブに新しいメディアが挿入されていないかを検査するようにボリューム管理に指示します。
.sp
.LP
デフォルトでは、ボリューム管理によって管理されている、検査が可能なすべてのメディアが \fBvolcheck\fR の対象となります。
.SH オプション
.sp
.LP
次のオプションがサポートされています。
.sp
.ne 2
.mk
.na
\fB\fB-i\fR\fI secs\fR\fR
.ad
.RS 11n
.rt  
デバイス検査の頻度を \fIsecs\fR 秒に設定します。デフォルトは 2 秒です。最小の頻度は 1 秒です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR\fI secs\fR\fR
.ad
.RS 11n
.rt  
\fIsecs\fR に指定される秒数の間、指定されたデバイスを検査します。指定できる最大の秒数は 28800 (8 時間) です。検査の頻度は \fB-i\fR で指定します。この合計時間にデフォルト値はありません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR\fR
.ad
.RS 11n
.rt  
冗長。
.RE

.SH オペランド
.sp
.LP
次のオペランドがサポートされています。
.sp
.ne 2
.mk
.na
\fB\fIpathname\fR\fR
.ad
.RS 12n
.rt  
メディアデバイスのパス名
.RE

.SH ファイル
.sp
.ne 2
.mk
.na
\fB\fB/dev/volctl\fR\fR
.ad
.RS 15n
.rt  
ボリューム管理の制御ポート
.RE

.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/storage/media-volume-manager
.TE

.SH 関連項目
.sp
.LP
\fBeject\fR(1), \fBrmmount\fR(1M), \fBattributes\fR(5)
