'\" te
.\"  Copyright 1989 AT&T Copyright (c) 1988 Sun Microsystems, Inc. - All Rights Reserved. Copyright (c) 1995 Sun Microsystems, Inc. All Rights Reserved.
.TH ypwhich 1 "1995 年 4 月 7 日" "SunOS 5.11" "ユーザーコマンド"
.SH 名前
ypwhich \- NIS サーバーまたはマップマスターの名前の表示
.SH 形式
.LP
.nf
\fBypwhich\fR [\fB-d\fR \fIdomain\fR] [ [\fB-t\fR] \fB-m\fR [\fImname\fR] | [\fB-Vn\fR] \fIhostname\fR]
.fi

.LP
.nf
\fBypwhich\fR \fB-x\fR
.fi

.SH 機能説明
.sp
.LP
\fBypwhich\fR は、NIS クライアントに NIS ネームサービスを提供している NIS サーバーの名前、またはマップのマスターである NIS サーバーの名前を返します。引数なしで呼び出した場合、このコマンドはローカルマシンの NIS サーバーを表示します。\fBhostname\fR を指定すると、そのマシンの照会が行われ、マシンで使用されている NIS マスターが表示されます。
.sp
.LP
NIS ネームサービスの概要については、\fBypfiles\fR(4) を参照してください。
.SH オプション
.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fI domain\fR\fR
.ad
.RS 13n
.rt  
デフォルトドメインの代わりに \fIdomain\fR を使用します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR\fR
.ad
.RS 13n
.rt  
マップのニックネームの使用を禁じます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-m\fR\fI mname\fR\fR
.ad
.RS 13n
.rt  
マップのマスター NIS サーバーを見つけます。\fB-m\fR を使用してホスト名を指定することはできません。\fB\fR\fImname\fR には、マップ名、またはマップのニックネームを指定できます。\fImname\fR を省略すると、使用可能なマップの一覧が生成されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-x\fR\fR
.ad
.RS 13n
.rt  
マップのニックネームの対応テーブルを表示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB\(miVn\fR\fR
.ad
.RS 13n
.rt  
\fBypbind\fR のバージョン。デフォルトは V3 です。
.RE

.SH 属性
.sp
.LP
属性についての詳細は、\fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件system/network/nis
.TE

.SH 関連項目
.sp
.LP
\fBypfiles\fR(4), \fBattributes\fR(5)
