#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#
#	This Makefile defines the build rules for the directory
#	uts/sun4u/grover.
#
#	The following two-level ordering must be maintained in this file.
#	  Lines are sorted first in order of decreasing specificity based on
#	  the first directory component.  That is, sun4u rules come before
#	  sparc rules come before common rules.
#
#	  Lines whose initial directory components are equal are sorted
#	  alphabetically by the remaining components.

#
#	Section 1a: C object build rules
#

# uts/sun4u/io/ppm.c is also used by xcalppm, which is open.
$(OBJS_DIR)/%.o:		$(UTSBASE)/sun4u/io/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSED)/sun4u/grover/io/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

#
#	Section 1b: Lint `object' build rules
#

# uts/sun4u/io/ppm.c is also used by xcalppm, which is open.
$(LINTS_DIR)/%.ln:		$(UTSBASE)/sun4u/io/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSED)/sun4u/grover/io/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))
