#
# Copyright (c) 2001, 2011, Oracle and/or its affiliates. All rights reserved.
#

include ../Makefile.com

install: stubinstall all $(ROOTLIBS) .WAIT $(ROOTLINKS) $(ROOTLINT) \
	$(ROOTSRCFILES)

stubinstall: stub $(STUBROOTLIBS) $(STUBROOTLINKS)
