'\" te
.\" Copyright (c) 2007, Sun Microsystems Inc. All Rights Reserved.
.TH trusted_extensions 5 "2007 年 11 月 12 日" "SunOS 5.11" "標準、環境、マクロ"
.SH 名前
trusted_extensions \- Solaris Trusted Extensions
.SH 機能説明
.sp
.LP
Solaris\u\s-2TM\s+2\d Trusted Extensions ソフトウェアは、Solaris オペレーティングシステム (Solaris OS) 構成の 1 つです。Solaris Trusted Extensions (Trusted Extensions) には、デスクトップシステム、ウィンドウシステム、ゾーンシステム、ファイルシステム、およびネットワーク通信用に、ローカルオブジェクトとローカルプロセスのラベルが提供されています。これらのラベルは、ラベルの関係に基づいて情報のフローを制限するマルチレベルセキュリティー (MLS) ポリシーの実装に使用されます。所有権に基づく随意アクセス制御 (Discretionary Access Control、DAC) とは異なり、Trusted Extensions によって適用される MLS ポリシーは必須アクセス制御 (Mandatory Access Control、MAC) の一例です。
.sp
.LP
デフォルトでは、Trusted Extensions ソフトウェアは無効になっています。これは、次の FMRI で識別される \fBlabeld\fR(1M) サービスによって有効化または無効化されます (ただし、構成はされません)。
.sp
.in +2
.nf
svc:/system/labeld:default
.fi
.in -2
.sp

.sp
.LP
Trusted Extensions ソフトウェアを使用する前に必要な構成については、下記の管理者ガイドを参照してください。Trusted Extensions ソフトウェアをアクティブ化または非アクティブ化するには、\fBlabeld\fR を有効または無効にしたあとでシステムをリブートする必要があります。
.SH 関連項目
.sp
.LP
\fBlabeld\fR(1M), \fBlabel_encodings\fR(4), \fBlabels\fR(5)
.sp
.LP
\fI『Oracle Solaris Trusted Extensions Configuration and Administration』\fR
.sp
.LP
\fI『Oracle Solaris Trusted Extensions User Guide』\fR
