#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 1996, 2011, Oracle and/or its affiliates. All rights reserved.
#

# cmd/cmd-inet/usr.lib/Makefile.lib

ROOTLIBINET=		$(ROOTLIB)/inet
ROOTLIBINET32=		$(ROOTLIBINET)/$(MACH32)
ROOTLIBINET64=		$(ROOTLIBINET)/$(MACH64)
ROOTLIBINETPROG=	$(PROG:%=$(ROOTLIBINET)/%)
ROOTLIBINETPROG32=	$(PROG:%=$(ROOTLIBINET32)/%)
ROOTLIBINETPROG64=	$(PROG:%=$(ROOTLIBINET64)/%)

STUBROOTLIBINET=	$(STUBROOTLIB)/inet
STUBROOTLIBINET32=	$(STUBROOTLIBINET)/$(MACH32)
STUBROOTLIBINET64=	$(STUBROOTLIBINET)/$(MACH64)
STUBROOTLIBINETPROG=	$(PROG:%=$(STUBROOTLIBINET)/%)
STUBROOTLIBINETPROG32=	$(PROG:%=$(STUBROOTLIBINET32)/%)
STUBROOTLIBINETPROG64=	$(PROG:%=$(STUBROOTLIBINET64)/%)

$(ROOTLIBINET)/%	$(STUBROOTLIBINET)/% \
$(ROOTLIBINET32)/%	$(STUBROOTLIBINET32)/% \
$(ROOTLIBINET64)/%	$(STUBROOTLIBINET64)/%: %
	$(INS.file)
