#
# Copyright (c) 2005, 2010, Oracle and/or its affiliates. All rights reserved.
#

MODULE = isp.so
MDBTGT = kvm

MODSRCS = isp.c

include $(SRC)/cmd/Makefile.cmd
include $(SRC)/cmd/Makefile.cmd.64
include $(SRC)/cmd/mdb/sparc/Makefile.sparcv9
include $(SRC)/cmd/mdb/Makefile.module
$(TONICBUILD)include $(CLOSED)/Makefile.tonic
