#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/libc_i18n/sparcv9/Makefile

include ../Makefile.com
include $(SRC)/lib/Makefile.lib.64

sparcv9_C_PICFLAGS=	-K PIC
EXTN_CFLAGS =	$(CCVERBOSE)
EXTN_CPPFLAGS =	-Dsparc
EXTN_LINTFLAGS=

install: all $(ROOTLIB_PIC64)
