/*
 * Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */

#include <sys/fm/cpu/GMCA.h>
#include <sys/mca_x86.h>
#include <sys/mca_amd.h>

#include "aamd.h"

/*
 * We usually have command names to match the ereport names that should
 * be logged when these commands are executed.  In the present case the
 * commands will inject some generic AMD errors, but the resulting
 * ereports will be generated by any one of the full model-specific support
 * (if present and enabled), generic AMD support (if present and enabled)
 * or generic x86 support.
 */
#define	_AAMD_PFX "generic-amd"
#define	_AAMD_CMNOPT "over,uc,pcc,*addrv,privaddr,ripv,en,otherinfo," \
	"mserrcode,addr,misc"
#define	_AAMD_CMDNAME(s) _AAMD_PFX "." s
#define	_AAMD_OPTS(cmdextra) cmdextra "," _AAMD_CMNOPT

#define	_AAMD_MEMOPTS "syndrome,scrubber," \
	"chip,*chan,*cs,ecccnt," \
	"chip2,chan2,cs2,ecccnt2"

#define	_AAMD_MEMERR \
	MCAX86_MKERRCODE_BUS_INTERCONNECT(MCAX86_ERRCODE_PP_SRC, \
	MCAX86_ERRCODE_T_NONE, MCAX86_ERRCODE_RRRR_RD, \
	MCAX86_ERRCODE_II_MEM, MCAX86_ERRCODE_LL_LG)

static const mtst_cmd_t aamd_cmds[] = {
	/*
	 * Correctable main memory 64/8 ECC error
	 */
	{ _AAMD_CMDNAME("mem_ce"), _AAMD_OPTS(_AAMD_MEMOPTS),
	    aamd_synthesize_nb,
	    _AAMD_MEMERR | AMD_BANK_STAT_CECC | AMD_BANK_MKSYND(0x1),
	    "Inject a 64/8 correctable main memory ECC error" },

	/*
	 * Uncorrectable main memory 64/8 ECC error
	 */
	{ _AAMD_CMDNAME("mem_ue"), _AAMD_OPTS(_AAMD_MEMOPTS),
	    aamd_synthesize_nb,
	    _AAMD_MEMERR | AMD_BANK_STAT_UECC | AMD_BANK_MKSYND(0x3) |
	    MSR_MC_STATUS_UC | MSR_MC_STATUS_PCC,
	    "Inject a 64/8 uncorrectable main memory ECC error" },

	/*
	 * Correctable main memory 128/16 ECC error
	 */
	{ _AAMD_CMDNAME("mem_ckce"), _AAMD_OPTS(_AAMD_MEMOPTS),
	    aamd_synthesize_nb,
	    _AAMD_MEMERR | AMD_BANK_STAT_CECC | AMD_NB_STAT_MKCKSYND(0xdd88) |
	    AMD_EXT_MKERRCODE(8),
	    "Inject a ChipKill correctable main memory ECC error" },

	/*
	 * Uncorrectable main memory 128/16 ECC error
	 */
	{ _AAMD_CMDNAME("mem_ckue"), _AAMD_OPTS(_AAMD_MEMOPTS),
	    aamd_synthesize_nb,
	    _AAMD_MEMERR | AMD_BANK_STAT_UECC | AMD_NB_STAT_MKCKSYND(0xffff) |
	    MSR_MC_STATUS_UC | MSR_MC_STATUS_PCC |
	    AMD_EXT_MKERRCODE(8),
	    "Inject a ChipKill uncorrectable main memory ECC error" },

	/*
	 * Add new commands above this line
	 */
	{ NULL, NULL, NULL, NULL, NULL }
};

static void
aamd_fini(void)
{
}

static const mtst_cpumod_ops_t aamd_cpumod_ops = {
	aamd_fini
};

static const mtst_cpumod_t aamd_cpumod = {
	MTST_CPUMOD_VERSION,
	"Generic AMD",
	&aamd_cpumod_ops,
	aamd_cmds
};

const mtst_cpumod_t *
_mtst_cpumod_init(void)
{
	return (&aamd_cpumod);
}
