#
# closed/uts/sun4u/mpxu/Makefile.files
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"%Z%%M%	%I%	%E% SMI"
#

#
#	Global definitions for sun4u implementation specific modules.
#

#
# Define objects.
#
MPXU_PLATMOD_OBJS	= mpxu.o
NTWDT_OBJS		= ntwdt.o

#
#	include mpxu header files
#
INC_PATH	+= -I$(UTSCLOSED)/sun4u -I$(UTSCLOSED)/sun4u/mpxu

include $(UTSBASE)/sun4u/mpxu/Makefile.files
