'\" te
.\" Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
.TH driver 4 "30 Jun 2011" "SunOS 5.11" "File Formats"
.SH NAME
driver \- user administered driver.conf
.SH SYNOPSIS
.sp
.LP
\fB/etc/driver/drv\fR
.SH DESCRIPTION
.sp
.LP
The directory \fB/etc/driver/drv\fR is a location where administrative \fBdriver.conf\fR customizations can be placed. 
.sp
.LP
Separating vendor \fBdriver.conf\fR files and administratively-customized \fBdriver.conf\fR files allows the system to be upgraded with new vendor \fBdriver.conf\fR files without overwriting the administrative customizations.
.SH SEE ALSO
.sp
.LP
\fBprtconf\fR(1M), \fBdriver.conf\fR(4), \fBddi_prop_exists\fR(9F), \fBddi_prop_lookup\fR(9F)
