'\" te
.\" Copyright (c) 2004, Sun Microsystems, Inc. All Rights Reserved.
.TH gsscred.conf 4 "17 Mar 2004" "SunOS 5.11" "File Formats"
.SH NAME
gsscred.conf \- Generic Security Services credential configuration file
.SH SYNOPSIS
.LP
.nf
\fB/etc/gss/gsscred.conf\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fBgsscred.conf\fR file contains GSS credential information including options that can be set by the system administrator.
.sp
.LP
The options that are in this file include:
.sp
.in +2
.nf
SYSLOG_UID_MAPPING=yes
.fi
.in -2

.sp
.LP
If this option is set to \fByes\fR, GSS cred to Unix cred mapping results will be logged to \fBsyslog\fR(3C) at level \fBauth.debug\fR.
.SH FILES
.sp
.ne 2
.mk
.na
\fB\fB/etc/gss/gsscred.conf\fR\fR
.ad
.RS 25n
.rt  
Contains GSS credential information.
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(5) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Interface StabilityCommitted
.TE

.SH SEE ALSO
.sp
.LP
\fBgsscred\fR(1M), \fBgssd\fR(1M), \fBsyslog\fR(3C), \fBkrb5.conf\fR(4), \fBattributes\fR(5), \fBkerberos\fR(5)
