'\" te
.\" Copyright (c) 2008, 2010, Oracle and/or its affiliates. All rights reserved.
.TH sock2path.d 4 "14 Sep 2010" "SunOS 5.11" "File Formats"
.SH NAME
sock2path.d \- socket mapping file that maps sockets to transport providers
.SH SYNOPSIS
.LP
.nf
\fB/etc/sock2path.d\fR
.fi

.SH DESCRIPTION
.sp
.LP
\fB/etc/sock2path.d\fR is a directory containing files with mappings between the \fBsocket\fR(3SOCKET) call parameters and the transport provider driver. The mapping file format is described in the \fBsoconfig\fR(1M) manual page.
.sp
.LP
The mappings in the \fBsock2path.d\fR directory are configured by the \fBsoconfig\fR utility at boot. The mappings are available to applications once the service management facility, \fBsmf\fR(5), reaches the single-user milestone:
.sp
.LP
\fBsvc:/milestone/single-user:default\fR
.SH EXAMPLES
.LP
\fBExample 1 \fRAn Example of a Mapping File
.sp
.LP
The following is an example of a mapping file:

.sp
.in +2
.nf
# Family    Type    Protocol    Module | Path 
     2       2         0          tcp 
     2       2         6          tcp 
     26      2         0          tcp 
     26      2         6          tcp 
     2       1         0          udp
     2       1        17          udp
    26       1         0          udp
    26       1        17          udp
     1       2         0          /dev/ticotsord
     1       6         0          /dev/ticotsord
     1       1         0          /dev/ticlts
     2       4         0          icmp
    26       4         0          icmp
    24       4         0          rts
    27       4         2          /dev/keysock
.fi
.in -2

.SH SEE ALSO
.sp
.LP
\fBinit\fR(1M), \fBsoconfig\fR(1M), \fBsocket\fR(3SOCKET), \fBsmf\fR(5)
