'\" te
.\" Copyright (c) 2008, Sun Microsystems, Inc.  All Rights Reserved
.\" Copyright 1989 AT&T 
.TH utmpx 4 "6 Mar 2008" "SunOS 5.11" "File Formats"
.SH NAME
utmpx, wtmpx \- utmpx and wtmpx database entry formats
.SH SYNOPSIS
.LP
.nf
\fB#include <utmpx.h>\fR
\fB/var/adm/utmpx\fR
\fB/var/adm/wtmpx\fR
.fi

.SH DESCRIPTION
.sp
.LP
The \fButmpx\fR and \fBwtmpx\fR files are extended database files that have superseded the obsolete \fButmp\fR and \fBwtmp\fR database files.
.sp
.LP
The \fButmpx\fR database contains user access and accounting information for commands such as \fBwho\fR(1), \fBwrite\fR(1), and \fBlogin\fR(1). The \fBwtmpx\fR database contains the history of user access and accounting information for the  \fButmpx\fR database. 
.SH USAGE
.sp
.LP
Applications should not access these databases directly, but should use the functions described on the \fBgetutxent\fR(3C) manual page to interact with the \fButmpx\fR and \fBwtmpx\fR databases to ensure that they are maintained consistently.
.SH FILES
.sp
.ne 2
.mk
.na
\fB\fB/var/adm/utmpx\fR\fR
.ad
.RS 18n
.rt  
user access and adminstration information
.RE

.sp
.ne 2
.mk
.na
\fB\fB/var/adm/wtmpx\fR\fR
.ad
.RS 18n
.rt  
history of user access and adminstrative information
.RE

.SH SEE ALSO
.sp
.LP
\fBgetutxent\fR(3C), \fBwait\fR(3C), \fBwait.h\fR(3HEAD)
