#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
#

. /lib/svc/share/smf_include.sh

case "$1" in
'start')
        uefi=$(/sbin/devprop -l efi-systab)
        if [ ! -z $uefi ]; then
            # vbiosd is not supported on UEFI systems (there is no VBIOS), so
            # disable the service until the next boot
            /usr/sbin/svcadm disable -t $SMF_FMRI
            exit $SMF_EXIT_OK
        fi
	if smf_is_nonglobalzone; then
		/usr/sbin/svcadm disable -t $SMF_FMRI
		echo "$SMF_FMRI is not supported in a local zone"
		sleep 5 &
		exit $SMF_EXIT_OK
	fi

	if [ `uname -i` == "i86xpv" ]; then
		/usr/sbin/svcadm disable $SMF_FMRI
		echo "$SMF_FMRI doesn't run in a PV domU"
		sleep 5 &
		exit $SMF_EXIT_OK
	fi

	/usr/sbin/vbiosd
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "WARNING: /usr/sbin/vbiosd failed"
		exit $SMF_EXIT_ERR_CONFIG
	fi
	;;


# the daemon is killed by :kill in the manifest. 	

*)
	echo "Usage: $0 { start }"
	exit 1
	;;

esac
exit 0
