'\" te
.\"  Copyright (c) 2005, 2011, Oracle and/or its affiliates.保留所有权利。
.TH adb 1 "2011 年 8 月 2 日" "SunOS 5.11" "用户命令"
.SH 名称
adb \- 通用调试器
.SH 用法概要
.LP
.nf
\fBadb\fR [\fB-kw\fR] [\fB-I\fR \fIdir\fR] [\fB-P\fR \fIprompt\fR] [\fB-V\fR \fImode\fR] [\fIobject\fR [\fIcore\fR]]
.fi

.SH 描述
.sp
.LP
\fBadb\fR 实用程序是一个交互式的通用调试器。它可用来检查文件并为程序的执行提供一个可控的环境。
.sp
.LP
目前，\fBadb\fR 实用程序是作为指向 \fBmdb\fR(1) 实用程序的链接实现的。\fBmdb\fR(1) 是一个低层次调试器，可用来检查用户进程以及当前操作系统或操作系统故障转储。新的 \fBmdb\fR(1) 实用程序完全向后兼容 \fBadb\fR 命令的现有语法和功能，包括支持处理 \fBadb\fR 宏文件。\fI《Oracle Solaris Modular Debugger Guide》\fR与 \fBmdb\fR(1) 手册页描述了 \fBmdb\fR 功能，包括其 \fBadb\fR 兼容性模式。在执行 \fBadb\fR 链接时，该兼容模式将缺省激活。
.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性developer/debug/mdb
.TE

.SH 另请参见
.sp
.LP
\fBmdb\fR(1)、\fBattributes\fR(5)
.sp
.LP
\fI《Oracle Solaris Modular Debugger Guide》\fR
