'\" te
.\"  版权所有 (c) 2009，Oracle 和/或其附属公司。保留所有权利
.TH audiotest 1 "2009 年 12 月 1 日" "SunOS 5.11" "用户命令"
.SH 名称
audiotest \- 测试音频设备
.SH 用法概要
.LP
.nf
\fBaudiotest\fR [\fB-24571\fR] [\fIdev\fR] ...
.fi

.SH 描述
.sp
.LP
\fBaudiotest\fR 实用程序对指定的音频设备运行测试（如果未指定音频设备，则对系统上找到的所有音频设备运行测试）。测试包括通过每个声道播放音频样例并测量回放的时钟偏移率。
.SH 选项
.sp
.LP
支持下列选项：
.sp
.ne 2
.mk
.na
\fB\fB-1\fR\fR
.ad
.RS 6n
.rt  
循环模式。测试运行进入死循环。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-2\fR\fR
.ad
.RS 6n
.rt  
立体声（双声道）模式。这是缺省模式。回放假定存在 2 个声道。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-4\fR\fR
.ad
.RS 6n
.rt  
四声道模式（4 声道环绕声）。测试假定存在四个环绕声声道。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-5\fR\fR
.ad
.RS 6n
.rt  
环绕声模式 (5.1)。该测试将检查左、右、环绕声左、环绕声右和中央声道。不测试低频音效声道。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-7\fR\fR
.ad
.RS 6n
.rt  
环绕声模式 (7.1)。该测试将检查左、右、环绕声左、环绕声右、后环绕声左、后环绕声右和中央声道。不测试低频音效声道。
.RE

.SH 操作数
.sp
.ne 2
.mk
.na
\fB\fIdev\fR\fR
.ad
.RS 7n
.rt  
要测试的设备的路径，例如 \fB/dev/dsp0\fR。
.RE

.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
体系结构SPARC、x86
_
可用性audio/audio-utilities
_
接口稳定性Committed（已确定）
.TE

.SH 另请参见
.sp
.LP
\fBaudioconvert\fR(1)、\fBaudioctl\fR(1)、\fBaudiorecord\fR(1)、\fBattributes\fR(5)、\fBaudio\fR(7I)
.SH 已知问题
.sp
.LP
\fBaudiotest\fR 无法检测物理设备支持的实际音频通道的数量。
.sp
.LP
\fBaudiotest\fR 不测试低频音效 (low-frequency effects, LFE) 声道。
.sp
.LP
不测试音频捕获、音量控制或其他高级设备功能。
