'\" te
.\" Copyright 2006, 2011, Oracle and/or its affiliates. 保留所有权利。
.TH digest 1 "2011 年 4 月 29 日" "SunOS 5.11" "用户命令"
.SH 名称
digest \- 计算消息摘要
.SH 用法概要
.LP
.nf
\fB/usr/bin/digest\fR \fB-l\fR | [\fB-v\fR] \fB-a\fR \fIalgorithm\fR [\fIfile\fR]...
.fi

.SH 描述
.sp
.LP
\fBdigest\fR 实用程序使用指定算法计算给定文件或 \fBstdin\fR 的消息摘要。如果指定多个文件，则输出的每一行都是一个文件的摘要。
.SH 选项
.sp
.LP
支持下列选项：
.sp
.ne 2
.mk
.na
\fB\fB-a\fR \fIalgorithm\fR\fR
.ad
.RS 16n
.rt  
指定加密或解密过程中要使用的算法的名称。有关详细信息，请参见"用法"下的\fB算法\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-l\fR\fR
.ad
.RS 16n
.rt  
显示系统上可用的算法的列表。此列表可依加密框架的配置而变化。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR\fR
.ad
.RS 16n
.rt  
详细输出。在输出中包括算法名称和文件名。
.RE

.SH 用法
.SS "算法"
.sp
.LP
这些算法由加密框架提供。该命令支持的每种算法都是 PKCS #11 机制的一个别名，这样有助于简化访问。例如，\fBsha1\fR 是 \fBCKM_SHA_1\fR 的别名。
.sp
.LP
这些别名与 \fB-a\fR 选项一起使用，并且区分大小写。
.SH 示例
.LP
\fB示例 1 \fR模拟输出
.sp
.LP
以下示例模拟通用的 \fBmd5sum\fR 程序的输出：

.sp
.in +2
.nf
example$ digest -v -a md5 /usr/bin/vi
md5 (/usr/bin/vi) = e4e3588c5212903847c66d36b1a828a5
.fi
.in -2
.sp

.LP
\fB示例 2 \fR生成文件摘要
.sp
.LP
以下示例生成文件 \fB/etc/motd\fR 的 \fBsha1\fR 摘要：

.sp
.in +2
.nf
example$ digest -a sha1 /etc/motd
9498a4f5303d056ad3ecae826b59f41448d63790
.fi
.in -2
.sp

.LP
\fB示例 3 \fR生成目录清单
.sp
.LP
以下示例生成 \fBsha1\fR 的目录清单：

.sp
.in +2
.nf
example$ digest -v -a sha1 /usr/lib/inet/*
sha1 (/usr/lib/inet/certdb) = f6d43e6e395d50db24d34e4af4828598c8918b16
sha1 (/usr/lib/inet/certlocal) = 7f74ba4a019b809c7023212b4bda10d9485e071d
sha1 (/usr/lib/inet/certrldb) = 1f845d30b8d02066647de04311e74549049852ed
sha1 (/usr/lib/inet/dhcp) = e3db5e4ff40a69d13f2497254526c2015d2c37b3
sha1 (/usr/lib/inet/dsvclockd) = b61aad7ed6a0f82145c3c26aedc613ab4a1f032e
sha1 (/usr/lib/inet/in.dhcpd) = 382210180c826fbb2e747236c489062bac8cc30b
sha1 (/usr/lib/inet/in.iked) = be6061fad725d37256e773dc85f8bd5248649463
sha1 (/usr/lib/inet/in.mpathd) = 5bd6bf0340fd5c4cc0c53f2df158302a0e85f9d0
sha1 (/usr/lib/inet/in.ndpd) = fdb768aebe7e5eb4465e1c1bb5e679b496f5c5c6
sha1 (/usr/lib/inet/in.ripngd) = 4f56a0df2d4a252f581a73c2e84143b920d0b66b
sha1 (/usr/lib/inet/ncaconfd) = 7219542b5585a8d1104d7ce4a2ced07d8a260ea3
sha1 (/usr/lib/inet/ppp) = c96ee458549871a6ffdf2674a888b01d0c9e9740
sha1 (/usr/lib/inet/pppoec) = 5f022498d79dacacd947cddadc64f171822e3dee
sha1 (/usr/lib/inet/pppoed) = 252bd2f0863dbc1b05fffae72821a2a95609b8ad
sha1 (/usr/lib/inet/slpd) = dfa24cc0f0b05f790546d4f0948a9094f7089027
sha1 (/usr/lib/inet/wanboot) = a8b8c51c389c774d0be2ae43cb85d1b1439484ae
sha1 (/usr/lib/inet/ntpd) = 5b4aff102372cea801e7d08acde9655fec81f07c
.fi
.in -2
.sp

.LP
\fB示例 4 \fR显示可用算法的列表
.sp
.LP
以下示例显示可用于生成摘要的算法的列表：

.sp
.in +2
.nf
example$ digest -l
sha1
md5
sha256
sha385
sha512
.fi
.in -2
.sp

.SH 退出状态
.sp
.LP
将返回以下退出值：
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 6n
.rt  
成功完成。
.RE

.sp
.ne 2
.mk
.na
\fB\fB>0\fR\fR
.ad
.RS 6n
.rt  
出现错误。
.RE

.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
_
接口稳定性Committed（已确定）
.TE

.SH 另请参见
.sp
.LP
\fBcksum\fR(1)、\fBencrypt\fR(1)、\fBmac\fR(1)、\fBbart\fR(1M)、\fBcryptoadm\fR(1M)、\fBlibpkcs11\fR(3LIB)、\fBattributes\fR(5)、\fBpkcs11_softtoken\fR(5)
