'\" te
.\" 版权所有 (c) 1996，Oracle 和/或其附属公司。保留所有权利。
.TH mach 1 "1996 年 1 月 18 日" "SunOS 5.11" "用户命令"
.SH 名称
mach \- 显示当前主机的处理器类型
.SH 用法概要
.LP
.nf
\fBmach\fR 
.fi

.SH 描述
.sp
.LP
\fBmach\fR 命令可显示当前主机的处理器类型。
.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
属性类型\fB\fR属性值\fB\fR
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBarch\fR(1)、\fBuname\fR(1)、\fBattributes\fR(5)
.SH 附注
.sp
.LP
\fBmach\fR 和 \fBuname\fR \fB-p\fR 返回等效值；因此鼓励独立软件供应商 (Independent Software Vendor, ISV) 和其他需要确定处理器类型的人将 \fBuname\fR 与 \fB-p\fR 选项配合使用，而不使用 \fBmach\fR 命令。提供 \fBmach\fR 命令是为了与之前的发行版兼容，但一般不鼓励使用它。
