'\" te
.\" 版权所有 1989 AT&T
.\" 版权所有 (c) 1990，2010，Oracle 和/或其附属公司。保留所有权利。
.TH machid 1 "2010 年 12 月 7 日" "SunOS 5.11" "用户命令"
.SH 名称
machid, sun, i386, i486, sparc \- 获取处理器类型实际值
.SH 用法概要
.LP
.nf
\fBsun\fR 
.fi

.LP
.nf
\fBi386\fR 
.fi

.LP
.nf
\fBsparc\fR 
.fi

.SH 描述
.sp
.LP
如果您使用命令名称指示的指令集，以下命令将返回 true 值（退出代码 0）。
.sp
.ne 2
.mk
.na
\fB\fBsun\fR\fR
.ad
.RS 9n
.rt  
如果您处于 Sun 系统上，则结果为 true。
.RE

.sp
.ne 2
.mk
.na
\fB\fBi386\fR\fR
.ad
.RS 9n
.rt  
如果您处于使用 iAPX386 处理器的计算机上，则结果为 true。
.RE

.sp
.ne 2
.mk
.na
\fB\fBsparc\fR\fR
.ad
.RS 9n
.rt  
如果您处于使用 SPARC 系列处理器的计算机上，则结果为 true。
.RE

.sp
.LP
不适用的命令将返回 false（非零）值。这些命令常在 makefile（请参见 \fBmake\fR(1S)）和 shell 脚本（请参见 \fBsh\fR(1)）内使用以增加可移植性。
.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBmake\fR(1S)、\fBsh\fR(1)、\fBtest\fR(1)、\fBtrue\fR(1)、\fBuname\fR(1)、\fBattributes\fR(5)
.SH 附注
.sp
.LP
命令的 \fBmachid\fR 系列已过时。请使用 \fBuname\fR \fB-p\fR 和 \fBuname\fR \fB-m\fR 作为代替。
