'\" te
.\"  版权所有 (c) 2003，Oracle 和/或其附属公司。保留所有权利。
.TH pagesize 1 "2001 年 5 月 4 日" "SunOS 5.11" "用户命令"
.SH 名称
pagesize \- 显示内存页面的大小
.SH 用法概要
.LP
.nf
\fB/usr/bin/pagesize\fR [\fB-a\fR]
.fi

.SH 描述
.sp
.LP
\fBpagesize\fR 实用程序输出内存页面的缺省大小（以字节为单位），与 \fBgetpagesize\fR(3C) 返回的内容相同。此程序在构造可移植 shell 脚本时非常有用。
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB-a\fR\fR
.ad
.RS 6n
.rt  
输出系统支持的所有可能的硬件地址转换大小。
.RE

.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/core-os
.TE

.SH 另请参见
.sp
.LP
\fBppgsz\fR(1)、\fBgetpagesize\fR(3C)、\fBgetpagesizes\fR(3C)、\fBattributes\fR(5)
