'\" te
.\" 版权所有 (c) 2007，Oracle 和/或其附属公司。保留所有权利。
.TH plabel 1 "2007 年 7 月 20 日" "SunOS 5.11" "用户命令"
.SH 名称
plabel \- 获取进程的标签
.SH 用法概要
.LP
.nf
\fB/usr/bin/plabel\fR [\fB-sS\fR] [\fIpid\fR...]
.fi

.SH 描述
.sp
.LP
\fBplabel\fR 是一个 proc 工具命令，用于获取进程的标签。如果未指定 \fIpid\fR，则显示的标签是 \fBplabel\fR 命令的标签。未指定这些选项时，标签的输出格式会以缺省格式显示。
.SH 选项
.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fR
.ad
.RS 6n
.rt  
以短格式显示与 \fIpid\fR 关联的标签。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-S\fR\fR
.ad
.RS 6n
.rt  
以长格式显示与 \fIpid\fR 关联的标签。
.RE

.SH 退出状态
.sp
.LP
\fBplabel\fR 退出时返回下列值之一：
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
成功完成。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
由于用法错误而无法成功完成。
.RE

.sp
.ne 2
.mk
.na
\fB\fB2\fR\fR
.ad
.RS 5n
.rt  
无法转换标签。
.RE

.sp
.ne 2
.mk
.na
\fB\fB3\fR\fR
.ad
.RS 5n
.rt  
无法分配内存。
.RE

.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/trusted
_
接口稳定性请参见下文。
.TE

.sp
.LP
\fBplabel\fR 实用程序是 "Committed"（已确定）。输出是 Not-an-Interface。
.SH 另请参见
.sp
.LP
\fBproc\fR(1)、\fBgetplabel\fR(3TSOL)、\fBattributes\fR(5)
.SH 附注
.sp
.LP
仅当系统配置有 Trusted Extensions 时，本手册页中介绍的功能才可用。
