'\" te
.\"  Copyright (c) 1995, 2011, Oracle and/or its affiliates. 保留所有权利。
.TH symorder 1 "2011 年 6 月 8 日" "SunOS 5.11" "用户命令"
.SH 名称
symorder \- 重新排列符号列表
.SH 用法概要
.LP
.nf
\fBsymorder\fR [\fB-s\fR] \fIobjectfile\fR \fIsymbolfile\fR
.fi

.SH 描述
.sp
.LP
\fBsymorder\fR 专门在 SunOS 4.\fIx\fR 中使用，以便削减获取 \fBvmunix\fR 中的符号所产生的系统开销。通过 \fB/dev/ksyms\fR 动态获取内核符号项时，该选项不再适用。
.sp
.LP
提供该脚本是为了方便需要维护在不同操作系统中可移植的脚本的软件开发人员。
.SH 退出状态
.sp
.LP
\fBsymorder\fR 退出状态为 \fB0\fR。
.SH 属性
.sp
.LP
有关下列属性的描述，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
lw(2.75i) lw(2.75i) 
lw(2.75i) lw(2.75i) 
.
属性类型\fB\fR\fB属性值\fR
可用性developer/base-developer-utilities
.TE

.SH 另请参见
.sp
.LP
\fBnlist\fR(3ELF)、\fBattributes\fR(5)、\fBksyms\fR(7D)。
