#
# Copyright (c) 2007, 2010, Oracle and/or its affiliates. All rights reserved.
#

UTSTREE=$(UTSCLOSED)

include $(UTSBASE)/sparc/Makefile.sparc.shared
$(TONICBUILD)include $(UTSCLOSED)/../Makefile.tonic

#
# Ensure that the variable member of the cpu_t (cpu_m) is defined
# for the lint builds so as not to cause lint errors during the
# global cross check.
#
$(LINTFLAGSUPPRESS)LINTFLAGS	+= -D_MACHDEP -I$(UTSBASE)/sun4 \
				-I$(UTSBASE)/sun4u -I$(UTSBASE)/sfmmu
