#ifndef __FW_DEFS_H__
#define __FW_DEFS_H__

#define BCM_5710_FW_MAJOR_VERSION			6
#define BCM_5710_FW_MINOR_VERSION			4
#define BCM_5710_FW_REVISION_VERSION		37
#define BCM_5710_FW_ENGINEERING_VERSION		0
#define BCM_5710_FW_COMPILE_FLAGS			1

#endif //__FW_DEFS_H__=======
