#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# uts/sun/Makefile.rules
#
#	This Makefile defines all build rules for the directory uts/sun and
# its children. These are the source files which are common to all sun
# implementations.
#
#	The following two-level ordering must be maintained in this file.
#	  Lines are sorted first in order of decreasing specificity based on
#	  the first directory component.  That is, sun4u rules come before
#	  sparc rules come before common rules.
#
#	  Lines whose initial directory components are equal are sorted
#	  alphabetically by the remaining components.

UTSCLOSEDSUN = $(UTSCLOSED)/sun

#
#	Section 1a: C object build rules
#

$(OBJS_DIR)/%.o:		$(UTSCLOSEDSUN)/io/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDSUN)/io/dada/adapters/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/%.o:		$(UTSCLOSEDSUN)/io/dada/adapters/ghd/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

$(OBJS_DIR)/ifp.o	:=	CFLAGS += -dalign
$(OBJS_DIR)/isp.o	:=	CFLAGS += -dalign
$(OBJS_DIR)/%.o:		$(UTSCLOSEDSUN)/io/scsi/adapters/%.c
	$(COMPILE.c) -o $@ $<
	$(CTFCONVERT_O)

#
#	Section 1b: Lint `object' build rules
#

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDSUN)/io/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDSUN)/io/dada/adapters/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDSUN)/io/dada/adapters/ghd/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))

$(LINTS_DIR)/%.ln:		$(UTSCLOSEDSUN)/io/scsi/adapters/%.c
	@($(LHEAD) $(LINT.c) $< $(LTAIL))
