#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"
#
# lib/raidcfg_plugins/mpt/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS)
