'\" te
.\" 版权所有 (c) 2008，Oracle 和/或其附属公司。保留所有权利。
.TH ad 5 "2008 年 10 月 22 日" "SunOS 5.11" "标准、环境和宏"
.SH 名称
ad \- Active Directory 用作命名系统信息库
.SH 描述
.sp
.LP
Solaris 客户机可以从 Active Directory (AD) 服务器获取命名信息。 
.sp
.LP
Solaris 系统必须首先加入 AD 域，然后再将 \fBad\fR 关键字添加到 \fBnsswitch.conf\fR(4) 文件的相应条目中。Solaris 系统通过使用 \fBkclient\fR(1M) 实用程序来加入 AD 域。AD 名称服务仅对 \fBpasswd\fR 和 \fBgroup\fR 支持命名数据库。
.sp
.LP
Windows 用户无法登录。\fBuser_attr\fR(4) 数据库不包含 Windows 用户的对应条目，并且 \fBpasswd\fR(1) 命令不支持与 AD 之间同步用户口令。
.sp
.LP
Solaris AD 客户机使用自动搜索方法查找 AD 目录服务器，例如，域控制器和全局目录服务器。客户机还使用 LDAP v3 协议访问 AD 服务器中的命名信息。由于 AD 客户机与本机 AD 模式协同工作，因此无需修改 AD 服务器模式。Solaris AD 客户机使用 \fBidmap\fR(1M) 服务在 Windows 安全标识符 (security identifier, SID) 和 Solaris 用户标识符 (user identifier, UID) 及组标识符 (group identifier, GID) 之间映射。用户名和组名源自 AD 用户和组对象的 \fBsAMAccountName\fR 属性，这些名称使用对象所在的域进行标记。使用 \fB@\fR 字符分隔域名和用户名或组名。 
.sp
.LP
客户机使用 SASL/GSSAPI/KRB5 安全模型。\fBkclient\fR 实用程序用于将客户机加入到 AD。执行加入操作时，\fBkclient\fR 在客户机上配置 Kerberos v5。请参见 \fBkclient\fR(1M)。
.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB/etc/nsswitch.conf\fR\fR
.ad
.RS 24n
.rt  
用于名称服务转换的配置文件。
.RE

.sp
.ne 2
.mk
.na
\fB\fB/etc/nsswitch.ad\fR\fR
.ad
.RS 24n
.rt  
使用 ad、dns 和文件配置的名称服务转换的样例配置文件。
.RE

.sp
.ne 2
.mk
.na
\fB\fB/usr/lib/nss_ad.so.1\fR\fR
.ad
.RS 24n
.rt  
AD 的名称服务转换模块。
.RE

.SH 另请参见
.sp
.LP
\fBpasswd\fR(1)、\fBsvcs\fR(1)、\fBidmap\fR(1M)、\fBidmapd\fR(1M)、\fBkclient\fR(1M)、\fBsvcadm\fR(1M)、\fBsvccfg\fR(1M)、\fBsvccfg\fR(1M)、\fBnsswitch.conf\fR(4)、\fBuser_attr\fR(4)、\fBsmf\fR(5)
