'\" te
.\" Copyright (c) 2009, 2011, Oracle and/or its affiliates. 保留所有权利。
.TH brands 5 "2011 年 7 月 8 日" "SunOS 5.11" "标准、环境和宏"
.SH 名称
brands \- 非全局区域的备用操作环境
.SH 描述
.sp
.LP
标记区域 (Branded Zone, BrandZ) 框架扩展了 \fBzones\fR(5) 中介绍的 Solaris Zones 基础结构，在其中包含标记创建功能，这些标记提供包含非本机操作环境的非全局区域。
.sp
.LP
术语"标记"可以指各种操作环境。所有标记管理都通过扩展当前区域结构来执行。
.sp
.LP
每个区域都配有一个关联标记。标记类型用来确定安装和引导区域时执行的脚本。此外，区域的标记还可用来在应用程序启动时确定正确的应用程序类型。缺省标记由全局区域中安装的分发软件决定。
.sp
.LP
一个标记区域只支持一个非本地二进制命令标记，这意味着一个标记区域只提供一种操作环境。一旦为区域分配了标记，便不能更改或删除该标记。
.sp
.LP
BrandZ 通过以下方式来扩展区域工具：
.RS +4
.TP
.ie t \(bu
.el o
标记是区域的一个属性，在创建区域时设置。
.RE
.RS +4
.TP
.ie t \(bu
.el o
zonecfg 工具（参见 \fBzonecfg\fR(1M)）用于设置区域的标记类型并配置区域。
.RE
.RS +4
.TP
.ie t \(bu
.el o
zoneadm 工具（参见 \fBzoneadm\fR(1M)）用于报告区域的标记类型并管理区域。
.RE
.SS "设备支持"
.sp
.LP
每个区域支持的设备都记录在该标记的手册页和其他文档中。区域基础结构检测任何尝试添加不支持设备的操作并向管理员发出警告。如果管理员不顾警告而选择添加不支持的设备，该设备可能无法如预期那样工作。该配置将会是未经过测试的，并且不受支持。
.SH 属性
.sp
.LP
有关以下属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性system/zones
_
接口稳定性Committed（已确定）
.TE

.SH 另请参见
.sp
.LP
\fBmdb\fR(1)、\fBzlogin\fR(1)、\fBzonename\fR(1)、\fBdtrace\fR(1M)、\fBin.rlogind\fR(1M)、\fBsshd\fR(1M)、\fBzoneadm\fR(1M)、\fBzonecfg\fR(1M)、\fBkill\fR(2)、\fBpriocntl\fR(2)、\fBgetzoneid\fR(3C)、\fBucred_get\fR(3C)、\fBgetzoneid\fR(3C)、\fBproc\fR(4)、\fBattributes\fR(5)、\fBsolaris\fR(5)、\fBprivileges\fR(5)、\fBsolaris10\fR(5)、\fBzones\fR(5)、\fBcrgetzoneid\fR(9F)
