'\" te
.\" 版权所有 (c) 2006，Oracle 和/或其附属公司。保留所有权利
.TH hal 5 "2006 年 9 月 11 日" "SunOS 5.11" "标准、环境和宏"
.SH 名称
hal \- 硬件抽象层概述
.SH 描述
.sp
.LP
硬件抽象层 (Hardware Abstraction Layer, HAL) 提供了连接到系统的各种硬件的视图。当硬件配置通过热插拔或其他机制发生更改时，此视图也将随之进行动态更新。HAL 将硬件表示为设备对象。设备对象由唯一标识符进行标识并带有一组键/值对，这些键/值对称为设备属性。有些属性源自实际硬件，有些属性由设备信息文件（\fB\&.fdi\fR 文件）合并而来，有些属性与实际设备配置相关。
.sp
.LP
HAL 通过 D-Bus 提供简单易用的 API。D-Bus 是一种 IPC 框架，在其功能中提供了使应用程序可以相互通话的系统范围的消息总线。具体来说，D-Bus 提供了异步通知，使 HAL 可以在添加和删除设备以及设备的属性发生更改时通知消息总线上的其他对等方。
.sp
.LP
在 Solaris 操作系统上，HAL 由守护进程、\fBhald\fR(1M) 和一组实用程序（用于添加和删除设备以及修改设备的属性）提供支持。
.SH 另请参见
.sp
.LP
\fBhald\fR(1M)、\fBfdi\fR(4)
.sp
.LP
请参见以下网址上的 HAL 页，包括 HAL 规范：http://freedesktop.org。
