'\" te
.\" 版权所有 (c) 2008，Oracle 和/或其附属公司。保留所有权利。
.TH smf_restarter 5 "2008 年 5 月 23 日" "SunOS 5.11" "标准、环境和宏"
.SH 名称
smf_restarter \- 重启程序的服务管理工具约定
.SH 描述
.sp
.LP
服务管理工具中的所有服务实例都必须由重启程序来管理。本手册页介绍该框架中所有重启程序共有的配置、功能和报告特性。特定重启程序独有的特性将在重启程序的手册页中介绍。
.sp
.LP
对于每个管理服务，重启程序依赖在服务实例上检索属性来确定配置。重启程序管理一组属性组，以此向显示工具（如 \fBsvcs\fR(1)）传送服务的当前处置情况。
.SS "服务配置"
.sp
.LP
所有服务的常见重启程序配置均在 \fBgeneral\fR 属性组中捕获。此组包含以下必需和可选的属性设置。
.sp
.ne 2
.mk
.na
\fB\fBenabled\fR\fR
.ad
.RS 19n
.rt  
此属性是必需的。如果设置此属性，实例的重启程序会尝试维护服务的可用性。
.RE

.sp
.ne 2
.mk
.na
\fB\fBrestarter\fR\fR
.ad
.RS 19n
.rt  
此属性是可选的，允许指定备用重启程序管理服务实例。如果 restarter 属性为空或缺失，则重启程序缺省为 \fBsvc.startd\fR(1M)。
.RE

.sp
.ne 2
.mk
.na
\fB\fBsingle_instance\fR\fR
.ad
.RS 19n
.rt  
此属性是可选的。如果设置此属性，在任意时间将只允许一个服务实例转换为联机或降级状态。
.RE

.SS "服务报告"
.sp
.LP
所有重启程序均使用 \fBrestarter\fR 属性组报告状态，该属性组包含以下属性：
.sp
.ne 2
.mk
.na
\fB\fBnext_state\fR\fR
.ad
.RS 19n
.rt  
存储在这些属性中的实例的当前状态和下一状态（如果当前处于转换中）。有关可能的状态的说明，参见 \fBsmf\fR(5)。
.RE

.sp
.ne 2
.mk
.na
\fB\fBauxiliary_state\fR\fR
.ad
.RS 19n
.rt  
一个不带空格的 astring，包含描述完整重启程序特定的状态以及重启程序状态属性的准确术语。不能一直设置辅助状态，在从任何状态进行转换期间应始终将其清除。每个重启程序都必须定义它所使用的辅助状态的精确列表。
.RE

.sp
.ne 2
.mk
.na
\fB\fBstate_timestamp\fR\fR
.ad
.RS 19n
.rt  
访问当前状态的时间。
.RE

.sp
.ne 2
.mk
.na
\fB\fBcontract\fR\fR
.ad
.RS 19n
.rt  
执行服务实例所依据的主进程合同 ID（如果有）。
.RE

.SH 另请参见
.sp
.LP
\fBsvcs\fR(1)、\fBsvc.startd\fR(1M)、\fBservice_bundle\fR(4)、\fBsmf\fR(5)、\fBsmf_method\fR(5)
