'\" te
.\" 版权所有 (c) 2007，Oracle 和/或其附属公司。保留所有权利。
.TH trusted_extensions 5 "2007 年 11 月 12 日" "SunOS 5.11" "标准、环境和宏"
.SH 名称
trusted_extensions \- Solaris Trusted Extensions
.SH 描述
.sp
.LP
Solaris\u\s-2TM\s+2\d Trusted Extensions 软件是 Solaris 操作系统 (Solaris OS) 的特定配置。Solaris Trusted Extensions（下称 Trusted Extensions）为本地对象和进程、桌面和窗口系统、区域和文件系统以及网络通信提供标签。这些标签用于实现多层安全性 (MLS) 策略，以便根据标签关系来限制信息流。与基于所有权的自主访问控制 (DAC) 相反，Trusted Extensions 实施的 MLS 策略是强制访问控制 (MAC) 的一个示例。
.sp
.LP
缺省情况下，Trusted Extensions 软件是禁用的。该软件可以通过 FMRI 标识的 \fBlabeld\fR(1M) 服务启用和禁用（但不能配置）：
.sp
.in +2
.nf
svc:/system/labeld:default
.fi
.in -2
.sp

.sp
.LP
有关使用前必须执行的 Trusted Extensions 软件配置的信息，请参见下面列出的管理员指南。在启用或禁用 \fBlabeld\fR 后，必须重新引导系统才能激活或取消激活 Trusted Extensions 软件。
.SH 另请参见
.sp
.LP
\fBlabeld\fR(1M), \fBlabel_encodings\fR(4), \fBlabels\fR(5)
.sp
.LP
\fI《Oracle Solaris Trusted Extensions Configuration and Administration》\fR
.sp
.LP
\fI《Oracle Solaris Trusted Extensions User Guide》\fR
